//! OCCT BRepSweep_Trsf (TKPrim/BRepSweep) — the intermediate class of the
//! simple swept primitives built by moving a Shape with a Trsf.
//!
//! Source: BRepSweep_Trsf.hxx L43-194, BRepSweep_Trsf.cxx L36-201.
//!
//! Architecture difference (Rust has no inheritance): the C++
//! `BRepSweep_NumLinearRegularSweep <- BRepSweep_Trsf <- Translation/Rotation`
//! chain maps to the composition roots owning a [`TrsfData`] member plus the
//! [`BRepSweepTrsfSlots`] trait extension; the Trsf concrete methods (Init /
//! Process / SetContinuity) are generic functions over the trait.

use rcad_kernel::topo_shape::Shape;
use rcad_kernel::topods::{Orientation, ShapeType};

use rcad_kernel::geom::CurveEval;
use super::brep_sweep_iterator::BRepSweepIterator;
use super::num_linear_regular_sweep::NumLinearRegularSweepSlots;
use super::sweep_num_shape::SweepNumShape;
use super::sweep_num_shape_iterator::SweepNumShapeIterator;
use super::tool_rehost::{
    brep_adaptor_curve_continuity, brep_lprop_continuity,
    topods_sub_shapes,
};
use indexmap::IndexMap;

use crate::brep_algo::tool::{brep_tool_curve, brep_tool_parameter, brep_tool_tolerance, shape_key};

/// The Trsf members (BRepSweep_Trsf.hxx L192-193).
///
/// Architecture difference: OCCT `TopLoc_Location myLocation` wraps a
/// gp_Trsf; the rcad location travels as a DAffine3 value (TopLoc semantics:
/// identity when default).  The `my_move_memo` carries the sharing identity
/// of the Move forms: OCCT `TopoDS_Shape::Move` keeps the SAME TShape under
/// a location, so every Move of one base TShape yields one located handle;
/// the pool-free deep-transform copy keeps that identity through this
/// per-sweep memo (same device as the kernel vert_by_pos caches).
#[derive(Debug, Clone)]
pub struct TrsfData {
    /// OCCT: myLocation.
    pub my_location: glam::DAffine3,
    /// OCCT: myCopy.
    pub my_copy: bool,
    /// The rcad Move-sharing memo (base TShape ptr -> moved copy).
    pub my_move_memo: std::cell::RefCell<indexmap::IndexMap<u64, Shape>>,
}

/// The BRepSweep_Trsf extension trait (the second inheritance level).
pub trait BRepSweepTrsfSlots: NumLinearRegularSweepSlots {
    /// The Trsf member access (the composition form of the C++ inheritance).
    fn trsf(&mut self) -> &mut TrsfData;
    fn trsf_ref(&self) -> &TrsfData;
}

/// OCCT BRepSweep_Trsf::Init() (cxx L47-57) — ends the construction of the
/// swept primitive, calling Process over the directing sub-shapes when the
/// basis elements are not shared.
pub fn init<T: BRepSweepTrsfSlots + ?Sized>(sl: &mut T) {
    if !sl.trsf_ref().my_copy {
        let gen_shape = sl.core_ref().my_gen_shape.clone();
        let dir_wire = sl.core_ref().my_dir_wire;
        let mut it = SweepNumShapeIterator::default();
        it.init(&dir_wire);
        while it.more() {
            let dir_v = *it.value();
            process(sl, &gen_shape, &dir_v);
            it.next();
        }
    }
}

/// OCCT BRepSweep_Trsf::Process(aGenS, aDirV) (cxx L59-93) — analyzes the
/// way of construction of the shapes generated by aGenS and aDirV; the
/// invariant (or non-transformed) sub-shapes are shared from the generatrix.
pub fn process<T: BRepSweepTrsfSlots + ?Sized>(sl: &mut T, a_gen_s: &Shape, a_dir_v: &SweepNumShape) -> bool {
    let dotrsf = a_dir_v.index() == 2 && !sl.core_ref().my_dir_wire.closed();
    let i_d = sl.core_ref().my_dir_shape_tool.index(a_dir_v);
    let i_g = sl.core_ref().my_gen_shape_tool.index(a_gen_s);
    if sl.is_invariant(a_gen_s) {
        sl.core().my_shapes.set(i_g, i_d, a_gen_s.clone());
        sl.core().my_built_shapes.set(i_g, i_d, true);
        true
    } else {
        let mut touch = false;
        let mut jt = BRepSweepIterator::default();
        jt.init(a_gen_s);
        while jt.more() {
            let sub = jt.value();
            if process(sl, &sub, a_dir_v) {
                touch = true;
            }
            jt.next();
        }
        if !touch || !dotrsf {
            let mut new_shape = a_gen_s.clone();
            if dotrsf {
                // OCCT: newShape.Move(myLocation) — the location move; the
                // rcad form is the sharing-preserving deep transform copy
                // (architecture difference: no TopLoc_Location table in the
                // pool-free shapes).  The memo is per-sweep (the TrsfData
                // member): OCCT Move of one base TShape always yields the
                // same located handle, so the Process-stored cells and the
                // parent containers share the copies.
                let location = sl.trsf_ref().my_location;
                let mut memo = sl.trsf().my_move_memo.borrow_mut();
                new_shape = top_loc_move(a_gen_s, &location, &mut memo);
            }
            sl.core().my_shapes.set(i_g, i_d, new_shape);
            sl.core().my_built_shapes.set(i_g, i_d, true);
        }
        touch
    }
}

/// OCCT TopoDS_Shape::Move(TopLoc_Location) — the whole shape relocated by
/// the transform.  The rcad pool-free form: a sharing-preserving deep copy
/// with the geometry transformed (vertex points, edge 3D curves, face
/// surfaces; pcurves, parameters, tolerances and the identity-preserved child
/// references are kept — rigid transforms preserve the parameterization).
pub fn top_loc_move(s: &Shape, t: &glam::DAffine3, memo: &mut IndexMap<u64, Shape>) -> Shape {
    if *t == glam::DAffine3::IDENTITY {
        return s.clone();
    }
    let key = s.ptr_id();
    if let Some(hit) = memo.get(&key) {
        return hit.clone();
    }
    use rcad_kernel::topods::{TVertexData, TEdgeData, TWireData, TFaceData, TShellData, TSolidData, TShape, tshape_flags};
    let new_data = match s.data.as_ref() {
        TShape::Vertex(vd) => {
            let new = TShape::Vertex(TVertexData {
                my_shapes: Vec::new(),
                flags: tshape_flags::DEFAULT,
                point: t.transform_point3(vd.point),
                tolerance: vd.tolerance,
                points: Vec::new(),
            });
            let sr = Shape {
                data: std::sync::Arc::new(new),
                index: usize::MAX,
                location: s.location,
                orientation: s.orientation,
            };
            memo.insert(key, sr.clone());
            return sr;
        }
        TShape::Edge(ed) => {
            // The children (the extremity vertices) move first, shared by
            // memo identity.
            let first = top_loc_move(&ed.first, t, memo);
            let last = top_loc_move(&ed.last, t, memo);
            TShape::Edge(TEdgeData {
                my_shapes: Vec::new(),
                flags: tshape_flags::DEFAULT,
                curve: ed.curve.as_ref().map(|c| rcad_kernel::geom::transform_curve(c, t)),
                first,
                last,
                range: ed.range,
                degenerated: ed.degenerated,
                pcurves: ed.pcurves.clone(),
                representations: ed.representations.clone(),
                vertex_params: ed.vertex_params.clone(),
                tolerance: ed.tolerance,
                same_parameter: ed.same_parameter,
                same_range: ed.same_range,
            })
        }
        TShape::Wire(wd) => {
            let edges = wd.edges.iter().map(|e| top_loc_move(e, t, memo)).collect();
            TShape::Wire(TWireData {
                my_shapes: Vec::new(),
                flags: tshape_flags::DEFAULT,
                edges,
            })
        }
        TShape::Face(fd) => {
            let outer = top_loc_move(&fd.outer_wire, t, memo);
            let inner = fd.inner_wires.iter().map(|w| top_loc_move(w, t, memo)).collect();
            TShape::Face(TFaceData {
                my_shapes: Vec::new(),
                flags: tshape_flags::DEFAULT,
                surface: fd.surface.as_ref().map(|s| rcad_kernel::geom::transform_surface(s, t)),
                surface_location: 0,
                outer_wire: outer,
                inner_wires: inner,
                sample_point: None,
                uv_domain: fd.uv_domain,
                internal_vertices: fd
                    .internal_vertices
                    .iter()
                    .map(|v| top_loc_move(v, t, memo))
                    .collect(),
                tolerance: fd.tolerance,
                natural_restriction: fd.natural_restriction,
            })
        }
        TShape::Shell(sd) => {
            let faces = sd.faces.iter().map(|f| top_loc_move(f, t, memo)).collect();
            TShape::Shell(TShellData {
                my_shapes: Vec::new(),
                flags: tshape_flags::DEFAULT,
                faces,
            })
        }
        TShape::Solid(sd) => {
            let shells = sd.shells.iter().map(|s| top_loc_move(s, t, memo)).collect();
            let internal_edges = sd
                .internal_edges
                .iter()
                .map(|e| top_loc_move(e, t, memo))
                .collect();
            TShape::Solid(TSolidData {
                my_shapes: Vec::new(),
                flags: tshape_flags::DEFAULT,
                shells,
                internal_vertices: sd
                    .internal_vertices
                    .iter()
                    .map(|v| top_loc_move(v, t, memo))
                    .collect(),
                internal_edges,
            })
        }
        TShape::CompSolid(cs) => {
            TShape::CompSolid(cs.iter().map(|s| top_loc_move(s, t, memo)).collect())
        }
        TShape::Compound(cd) => {
            TShape::Compound(cd.iter().map(|s| top_loc_move(s, t, memo)).collect())
        }
    };
    let sr = Shape {
        data: std::sync::Arc::new(new_data),
        index: usize::MAX,
        location: s.location,
        orientation: s.orientation,
    };
    memo.insert(key, sr.clone());
    sr
}

/// OCCT BRepSweep_Trsf::SetContinuity(aGenS, aDirS) (cxx L97-201) —
/// propagates the continuity of the generatrix vertices on the generated
/// edges and faces (tl = Precision::Confusion; ta = 0.00175, environ 0.1
/// degre).
pub fn set_continuity<T: BRepSweepTrsfSlots + ?Sized>(sl: &mut T, a_gen_s: &Shape, a_dir_s: &SweepNumShape) {
    // OCCT L99-101: constexpr tl = Precision::Confusion(); angular etant un
    // peu severe pour les contours sketches, ta = 0.00175 (environ 0.1
    // degre).
    let tl = rcad_kernel::precision::CONFUSION;
    let ta = 0.00175;
    if a_gen_s.shape_type() == ShapeType::Edge {
        if sl.has_shape(a_gen_s, a_dir_s) {
            // OCCT L108-113: E = Edge(aGenS); TopExp::Vertices(E, d, f).
            let (d, f) = {
                let (vf, vl) = crate::brep_algo::tool::top_exp_vertices_raw(a_gen_s);
                (vf, vl)
            };
            if let (Some(d), Some(f)) = (&d, &f) {
                if d.is_same(f) {
                    // OCCT L115-116: tol3d = max(tl, 2*Tolerance(d)) (IFV
                    // 24.05.00 buc60684).
                    let tol3d = tl.max(2.0 * brep_tool_tolerance(d));
                    let (curve, _first, _last) = match brep_tool_curve(a_gen_s) {
                        Some(hit) => hit,
                        None => return,
                    };
                    // OCCT L117-119: ud/uf = BRep_Tool::Parameter(d/f, E).
                    let ud = brep_tool_parameter(d, a_gen_s);
                    let uf = brep_tool_parameter(f, a_gen_s);
                    // OCCT L120: cont = BRepLProp::Continuity(e, e, ud, uf,
                    // tol3d, ta); the C1.Edge() orientation is aGenS's; the
                    // same-edge final condition is C1.IsPeriodic().
                    let reversed = a_gen_s.orientation == Orientation::Reversed;
                    let periodic = curve.is_periodic();
                    let cont = brep_lprop_continuity(
                        &curve,
                        &curve,
                        ud,
                        uf,
                        tol3d,
                        ta,
                        reversed,
                        reversed,
                        periodic,
                    );
                    // OCCT L121-128: if (cont >= 1) — the regularity between
                    // the generated edge and the generated face of the closed
                    // generatrix.
                    if cont >= super::tool_rehost::GEOM_ABS_G1 {
                        let mut s_wnt = sl.shape(d, a_dir_s);
                        let e_wnt = s_wnt.clone(); // TopoDS::Edge(s_wnt)
                        let _ = &mut s_wnt;
                        let s_wnt2 = sl.shape(a_gen_s, a_dir_s);
                        let f_wnt = s_wnt2; // TopoDS::Face(s_wnt)
                        sl.core_ref().my_builder.my_builder.continuity(
                            &e_wnt,
                            &f_wnt,
                            &f_wnt,
                            geom_abs_from_rank(cont),
                        );
                    }
                }
            }
            // OCCT L130-147: the closed directing edge case.
            if a_dir_s.closed() {
                let dirv = sl.core_ref().my_dir_shape_tool.shape(2);
                let sh1 = sl.shape(a_gen_s, a_dir_s);
                let sh2 = sl.shape(a_gen_s, &dirv);
                if sl.gdd_shape_is_to_add(&sh1, &sh2, a_gen_s, a_dir_s, &dirv) {
                    // OCCT L135-137: cont = BRep_Tool::Curve(E, Lo, fi,
                    // la)->Continuity() — the Geom_Curve's own continuity.
                    let cont = match brep_tool_curve(a_gen_s) {
                        Some((curve, _fi, _la)) => brep_adaptor_curve_continuity(&curve),
                        None => super::tool_rehost::GEOM_ABS_C0,
                    };
                    if cont >= super::tool_rehost::GEOM_ABS_G1 {
                        let mut s_wnt = sl.shape(a_gen_s, &dirv);
                        let e_wnt = s_wnt.clone(); // TopoDS::Edge(s_wnt)
                        let _ = &mut s_wnt;
                        let s_wnt2 = sl.shape(a_gen_s, a_dir_s);
                        let f_wnt = s_wnt2; // TopoDS::Face(s_wnt)
                        sl.core_ref().my_builder.my_builder.continuity(
                            &e_wnt,
                            &f_wnt,
                            &f_wnt,
                            geom_abs_from_rank(cont),
                        );
                    }
                }
            }
        }
    } else if a_gen_s.shape_type() == ShapeType::Wire {
        // OCCT L150-199: the wire case — the vertex/edge ancestor map
        // (TopExp::MapShapesAndAncestors(aGenS, VERTEX, EDGE, M)).
        let m = map_shapes_and_ancestors(a_gen_s, ShapeType::Vertex, ShapeType::Edge);
        for (_key, (v, ancestors)) in m.iter() {
            let v = v.clone();
            let lst = ancestors.clone();
            let mut it_idx = 0usize;
            let mut j = 1i32;
            while it_idx < lst.len() {
                let mut jt_idx = 0usize;
                // OCCT: Jt.Initialize(...); for (k = 1; k <= j; k++) Jt.Next();
                let mut k = 1;
                while k <= j {
                    jt_idx += 1;
                    k += 1;
                }
                while jt_idx < lst.len() {
                    let e1 = lst[it_idx].clone();
                    let e2 = lst[jt_idx].clone();
                    if !e1.is_same(&e2)
                        && sl.has_shape(&e1, a_dir_s)
                        && sl.has_shape(&e2, a_dir_s)
                    {
                        // OCCT L178-185: u1/u2 = BRep_Tool::Parameter(V, E1/E2);
                        // tol3d = max(tl, 2*Tolerance(V)) (IFV 24.05.00
                        // buc60684); cont = BRepLProp::Continuity(e1, e2, ...).
                        let u1 = brep_tool_parameter(&v, &e1);
                        let u2 = brep_tool_parameter(&v, &e2);
                        let tol3d = tl.max(2.0 * brep_tool_tolerance(&v));
                        let c1 = match brep_tool_curve(&e1) {
                            Some(hit) => hit.0,
                            None => continue,
                        };
                        let c2 = match brep_tool_curve(&e2) {
                            Some(hit) => hit.0,
                            None => continue,
                        };
                        let e1_reversed = e1.orientation == Orientation::Reversed;
                        let e2_reversed = e2.orientation == Orientation::Reversed;
                        let cont = brep_lprop_continuity(
                            &c1,
                            &c2,
                            u1,
                            u2,
                            tol3d,
                            ta,
                            e1_reversed,
                            e2_reversed,
                            false,
                        );
                        // OCCT L186-195: if (cont >= 1) — the regularity
                        // between the generated edge and both generated faces.
                        if cont >= super::tool_rehost::GEOM_ABS_G1 {
                            let mut s_wnt = sl.shape(&v, a_dir_s);
                            let e_wnt = s_wnt.clone(); // TopoDS::Edge(s_wnt)
                            let _ = &mut s_wnt;
                            let s_wnt2 = sl.shape(&e1, a_dir_s);
                            let f1_wnt = s_wnt2; // TopoDS::Face(s_wnt)
                            let s_wnt3 = sl.shape(&e2, a_dir_s);
                            let f2_wnt = s_wnt3; // TopoDS::Face(s_wnt)
                            sl.core_ref().my_builder.my_builder.continuity(
                                &e_wnt,
                                &f1_wnt,
                                &f2_wnt,
                                geom_abs_from_rank(cont),
                            );
                        }
                    }
                    jt_idx += 1;
                }
                it_idx += 1;
                j += 1;
            }
        }
    }
}

/// OCCT TopExp::MapShapesAndAncestors(S, TS, TA, M) (TopExp.cxx): the
/// ancestors of every TS sub-shape are collected by visiting the TA
/// sub-shapes and matching their direct TS children; the TS == TA self entry
/// closes the walk.
fn map_shapes_and_ancestors(
    s: &Shape,
    ts: ShapeType,
    ta: ShapeType,
) -> IndexMap<(u64, u32), (Shape, Vec<Shape>)> {
    let mut m: IndexMap<(u64, u32), (Shape, Vec<Shape>)> = IndexMap::new();
    // OCCT: visit the ancestors (TopExp_Explorer expa(S, TA)).
    for anc in crate::brep_algo::tool::explorer(s, ta, ShapeType::Shape) {
        // OCCT: visit the direct children (TopoDS_Iterator ita(anc)).
        for child in topods_sub_shapes(&anc) {
            if child.shape_type() == ts {
                let key = shape_key(&child);
                let entry = m.entry(key).or_insert_with(|| (child.clone(), Vec::new()));
                entry.1.push(anc.clone());
            }
        }
    }
    // OCCT: and the shape itself if TS == TA.
    if ts == ta && s.shape_type() == ts {
        let key = shape_key(s);
        let entry = m.entry(key).or_insert_with(|| (s.clone(), Vec::new()));
        entry.1.push(s.clone());
    }
    m
}

/// The GeomAbs_Shape rank -> rcad enum mapping (the BRep_Builder::Continuity
/// argument; the rank is the GeomAbs_Shape.hxx L47-56 order).
fn geom_abs_from_rank(rank: i32) -> rcad_kernel::topods::GeomAbsShape {
    use rcad_kernel::topods::GeomAbsShape as G;
    match rank {
        x if x <= super::tool_rehost::GEOM_ABS_C0 => G::C0,
        super::tool_rehost::GEOM_ABS_G1 => G::G1,
        super::tool_rehost::GEOM_ABS_C1 => G::C1,
        3 => G::G2,
        super::tool_rehost::GEOM_ABS_C2 => G::C2,
        super::tool_rehost::GEOM_ABS_C3 => G::C3,
        _ => G::CN,
    }
}
