//! OCCT AdvApp2Var (TKGeomBase/AdvApp2Var) - the 2-var adaptive approximation
//! stack consumed by GeomPlate_MakeApprox / GeomPlate_PlateG0Criterion.
//!
//! Landing order (bottom-up, 1:1; each landed piece carries its OCCT anchor):
//! - [`sys_base`]: the consumed subset of AdvApp2Var_SysBase
//!   (debug/zero/copy/alloc primitives; AdvApp2Var_SysBase.cxx).
//! - [`data_mlgdrtl`] / [`data_mmapgss`] / [`data_mmapgs0`] /
//!   [`data_mmapgs1`] / [`data_mmapgs2`] / [`data_mmjcobi`] /
//!   [`data_mmjcobi_b`] / [`data_mmcmcnp`]: the block-data tables
//!   (AdvApp2Var_Data_*.pxx), generated byte-faithfully from the C
//!   initializers.
//! - [`math_base`] / [`math_base_b`]: the consumed subset of
//!   AdvApp2Var_MathBase - pow__di, mfac_, mmdrc11_, mmrtptt_ (part A) and
//!   mzsnorm_, mmveps3_, mmeps1_, mmwprcs_ (MPRCSN common), mmapcmp_,
//!   mmaper0/2/4/6/x_, mmfmca8_, mmfmca9_, mmfmtb1_, mmjacan_, mmjaccv_,
//!   mmmpocur_, mmtrpjj_ + mmtrpj0/2/4/6 (part B).
//! - [`approxf2var_a`]: mma1her_, mma2ac1_, mma2ac2_, mma2ac3_ - the
//!   Patch::AddConstraints leaf set.
//! - [`approxf2var_b`]: mma2jmx_, mma2roo_, mmapptt_, mmmapcoe_, mmaperm_,
//!   mma2moy_, mma2fx6_ - the Context ctor / Jacobi-coefficient /
//!   degree-reduction set.
//! - [`approxf2var_c`]: mmjacpt_, mma1cdi_, mma1cnt_, mma1fdi_, mma1fer_,
//!   mma1jak_, mma1noc_, mma1nop_ + the [`approxf2var_c::EvaluatorFunc2Var`]
//!   port of AdvApp2Var_EvaluatorFunc2Var.hxx - the iso-discretization set.
//! - [`approxf2var_d`]: mma2can_, mma2cd1_, mma2cd2_, mma2cd3_, mma2cdi_ -
//!   the constraint-discretization set.
//! - [`approxf2var_e`]: mma2cfu_, mma2cfv_, mma2er1_, mma2er2_, mma2ce2_,
//!   mma2ce1_ - the coefficient/error engines and the zone driver.
//! - [`approxf2var_f`]: mma2ds1_, mma2ds2_, mma2fnc_ - the function
//!   discretization and the cut-managed approximation driver.
//!
//! The complete AdvApp2Var_ApproxF2var.cxx engine set and its MathBase /
//! SysBase dependencies are landed.  Remaining GAP leaves of the package
//! closure (each an annotated anchor for the next batch):
//! - MathBase statics not consumed by the landed engines (mmarc41_,
//!   mmgaus1_, mmresol_, ...; AdvApp2Var_MathBase.cxx).
//! - The class layer: AdvApp2Var_Node / Iso / Network / Framework / Patch /
//!   Context / Criterion / ApproxAFunc2Var (AdvApp2Var_*.cxx) over the
//!   kernel B-spline types, and PLib::EvalPolynomial / EvalPoly2Var
//!   (PLib.cxx L1055-1114) + the 12-arg Convert_GridPolynomialToPoles - the
//!   consumers GeomPlate_MakeApprox / GeomPlate_PlateG0Criterion::Value keep
//!   their OCCT failure paths until this layer lands.

pub mod approxf2var_a;
pub mod approxf2var_b;
pub mod approxf2var_c;
pub mod approxf2var_d;
pub mod approxf2var_e;
pub mod approxf2var_f;
pub mod data_mlgdrtl;
pub mod data_mmapgs0;
pub mod data_mmapgs1;
pub mod data_mmapgs2;
pub mod data_mmapgss;
pub mod data_mmjcobi;
pub mod data_mmjcobi_b;
pub mod data_mmcmcnp;
pub mod math_base;
pub mod math_base_b;
pub mod sys_base;