//! OCCT AdvApp2Var (TKGeomBase/AdvApp2Var) - the 2-var adaptive approximation
//! stack consumed by GeomPlate_MakeApprox / GeomPlate_PlateG0Criterion.
//!
//! Landing order (bottom-up, 1:1; each landed piece carries its OCCT anchor):
//! - [`sys_base`]: the consumed subset of AdvApp2Var_SysBase
//!   (debug/zero/copy/alloc primitives; AdvApp2Var_SysBase.cxx).
//! - [`data_mlgdrtl`] / [`data_mmapgss`] / [`data_mmapgs0`] /
//!   [`data_mmapgs1`] / [`data_mmapgs2`]: the block-data tables
//!   (AdvApp2Var_Data_*.pxx), generated byte-faithfully from the C
//!   initializers.
//! - [`math_base`]: the consumed subset of AdvApp2Var_MathBase
//!   (pow__di, mfac_, mmdrc11_, mmrtptt_).
//! - [`approxf2var_a`]: mma1her_, mma2ac1_, mma2ac2_, mma2ac3_
//!   (AdvApp2Var_ApproxF2var.cxx) - the Patch::AddConstraints leaf set.
//! - [`approxf2var_b`]: mma2jmx_, mma2roo_, mmapptt_, mmmapcoe_, mmaperm_,
//!   mma2moy_ - the Context ctor and Jacobi-coefficient leaf set.
//!
//! Remaining GAP leaves of the AdvApp2Var closure (each an annotated OCCT
//! anchor for the next batch, in bottom-up order):
//! - MathBase: mmjacan_ (L3117), mmjaccv_ (L5792), mmapcmp_, mmaperx_,
//!   mmfmca8_ (L3700 area), mmfmtb1_, mmmpocur_, mmtrpjj_, mmveps3_,
//!   mzsnorm_, mmfmca9_ (L3873), mmdrc11_ DONE, mmrtptt_ DONE.
//! - ApproxF2var: mma2cdi_ (L3366-3719), mma2ce1_ (L3719-4023) +
//!   mma2ce2_ (L4023-4998) + mma2cfu_ (L4998-5224) + mma2cfv_ (L5228-5383) +
//!   mma2er1_ + mma2er2_ + mma2can_ (L2205-3366), mma2ds1_ (L5383-6624) +
//!   mma2ds2_ + mma1fdi_ + mma1cdi_ + mma1cnt_ + mma1fer_ + mma1noc_ +
//!   mma1nop_ + mma1jak_ + mmjacpt_ + mmmapcoe_ DONE + mmaperm_ DONE,
//!   mma2fnc_ (L6624-7285), mma2fx6_ (L7285-7576).
//! - Classes: AdvApp2Var_Node / Iso / Network / Framework / Patch / Context /
//!   Criterion / ApproxAFunc2Var (AdvApp2Var_*.cxx) and the consumers
//!   GeomPlate_MakeApprox / GeomPlate_PlateG0Criterion::Value.
//!   PLib::EvalPoly2Var (PLib.cxx L1055-1114, over PLib::EvalPolynomial) and
//!   Convert_GridPolynomialToPoles complete the closure.

pub mod approxf2var_a;
pub mod approxf2var_b;
pub mod data_mlgdrtl;
pub mod data_mmapgs0;
pub mod data_mmapgs1;
pub mod data_mmapgs2;
pub mod data_mmapgss;
pub mod math_base;
pub mod sys_base;
