[package]
name = "rcad-oas"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/cad-rs/rcad"

[dependencies]
laykit = { workspace = true }
rcad-kernel = { path = "../rcad-kernel" }
rcad-modeling = { path = "../rcad-modeling" }
glam.workspace = true
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3"
