//! OCCT BRepFill_Evolved — 1:1 translation (part 2: ElementaryPerform).
//!
//! Source: $OCCT_SRC/src/ModelingAlgorithms/TKBool/BRepFill/
//!         BRepFill_Evolved.cxx L657-1263 (ElementaryPerform).
//! Consumes the shared data carriers of brep_fill_evolved.rs and the file
//! statics of brep_fill_evolved_d.rs.

use glam::DVec3;

use rcad_kernel::geom::{Curve2d, Curve3, CurveEval};
use rcad_kernel::topo_shape::Shape;
use rcad_kernel::topods::{Orientation, ShapeType};

use crate::brep_algo::tool::{
    builder_add_edge_vertex, builder_range_edge, builder_update_edge_pcurve,
    builder_update_vertex_point_tol, top_abs_reverse,
};
use crate::brep_fill::brep_fill_evolved::{
    arc_first_element, arc_first_node, arc_second_element, arc_second_node, basic_elt_start_arc,
    brep_fill_confusion, builder_add_compound_shape, builder_make_compound, builder_make_vertex,
    edge_vertices, node_on_basic_elt, wire_edges, BRepFillEvolved,
    BRepMAT2dBisectingLocusCarrier, BRepMAT2dLinkTopoBiloCarrier, DataMapOfShapeItem,
    DataMapOfShapeListOfShape, MapNodeVertex,
};
use crate::brep_fill::brep_fill_trim_edge_tool::GeomAbsJoinType;
use crate::brep_fill::brep_fill_trim_surface_tool::BRepFillTrimSurfaceTool;
use crate::brep_fill::generator::{shape_key, shape_oriented, ShapeKey};
use crate::topalgo::mat::HandleMatArc;

impl BRepFillEvolved {
    /// OCCT BRepFill_Evolved::ElementaryPerform(Sp, Pr, Locus, Link, Join)
    /// (L657-1263).  The Join parameter is unused in OCCT
    /// (`const GeomAbs_JoinType /*Join*/`).
    #[allow(clippy::too_many_arguments)]
    pub(super) fn elementary_perform(
        &mut self,
        sp: &Shape,
        pr: &Shape,
        locus: &BRepMAT2dBisectingLocusCarrier,
        link: &mut BRepMAT2dLinkTopoBiloCarrier,
        _join: GeomAbsJoinType,
    ) {
        // OCCT L664-668.
        let a_local_shape = shape_oriented(sp, Orientation::Forward);
        self.my_spine = a_local_shape;
        self.my_profile = pr.clone();
        self.my_map.clear();

        // OCCT L670-671: myBuilder; MakeCompound(myShape).
        self.my_shape = builder_make_compound();

        //---------------------------------------------------------------------
        // MapNodeVertex : associate to each node of the map (key1) and
        //                 to each element of the profile (key2) a vertex (item).
        // MapBis        : a set of edges or vertexes (item) generated by
        //                 a bisectrice on a face or an edge (key) of
        //                 tubes or revolutions.
        // MapVerPar     : Map of parameters of vertices on parallel edges
        //                 the list contained in MapVerPar (E) corresponds
        //                 to parameters on E of vertices contained in  MapBis(E);
        // MapBS         : links BasicElt of the map => Topology of the spine.
        //---------------------------------------------------------------------
        // OCCT L685-696.
        let mut map_node_vertex = MapNodeVertex::new();
        let mut map_bis: DataMapOfShapeListOfShape = DataMapOfShapeListOfShape::new();
        let mut map_ver_par: DataMapOfShapeItem<Vec<f64>> = DataMapOfShapeItem::new();

        // mark of the profile.
        // OCCT L699: gp_Ax3 AxeRef(gp_Pnt(0,0,0), gp_Dir(Z), gp_Dir(X)).
        let axe_ref = rcad_kernel::math::gp::Ax3::from_pnt_n_vx(DVec3::ZERO, DVec3::Z, DVec3::X);

        //---------------------------------------------------------------
        // Construction of revolutions and tubes.
        //---------------------------------------------------------------
        // OCCT L704-734.
        for face_exp_current in crate::brep_algo::tool::explorer(
            &self.my_spine.clone(),
            ShapeType::Wire,
            ShapeType::Shape,
        ) {
            for current_edge in wire_edges(&face_exp_current) {
                let (_v_first, v_last) = edge_vertices(&current_edge);

                // OCCT L718-724: for (Link.Init(VLast); Link.More();
                // Link.Next()) { MakeRevol(CurrentEdge, VLast, AxeRef); }.
                link.init(&v_last);
                while link.more() {
                    // Construction of a Revolution.
                    self.make_revol(&current_edge, &v_last, &axe_ref);
                    link.next();
                }

                // OCCT L726-732: for (Link.Init(CurrentEdge); Link.More();
                // Link.Next()) { MakePipe(CurrentEdge, AxeRef); }.
                link.init(&current_edge);
                while link.more() {
                    // Construction of a Tube.
                    self.make_pipe(&current_edge, &axe_ref);
                    link.next();
                }
            }
        }

        //---------------------------------------------------
        // Construction of edges associated to bissectrices.
        //---------------------------------------------------
        // OCCT L739-748.
        let mut bis: Option<Curve2d> = None;

        // OCCT L750-753: for (i = 1; i <= Locus.Graph()->NumberOfArcs(); i++)
        // { CurrentArc = Locus.Graph()->Arc(i); SimpleExpression(Locus.GeomBis(
        // CurrentArc, Reverse), Bis); }.
        let graph = locus.graph();
        let nb_arcs = graph.read().expect("MAT_Graph").number_of_arcs();
        for i in 1..=nb_arcs {
            let current_arc: HandleMatArc = graph.read().expect("MAT_Graph").arc(i);
            let mut reverse = false;
            let geom_bis = locus.geom_bis(&current_arc, &mut reverse);
            crate::brep_fill::brep_fill_evolved_d::simple_expression(&geom_bis, &mut bis);
            let bis = bis.clone().expect("SimpleExpression");

            //------------------------------------------------------------------
            // Return elements of the spine corresponding to separate basicElts.
            //------------------------------------------------------------------
            // OCCT L758-759.
            let s0 = link.generating_shape(&arc_first_element(&current_arc));
            let s1 = link.generating_shape(&arc_second_element(&current_arc));

            // OCCT L761-762.
            let concave0 = crate::brep_fill::brep_fill_evolved_d::concave_side(&s0, &self.my_spine.clone());
            let concave1 = crate::brep_fill::brep_fill_evolved_d::concave_side(&s1, &self.my_spine.clone());

            // OCCT L764-770.
            let mut v_on_f: Vec<Shape> = Vec::new();
            let mut v_on_l: Vec<Shape> = Vec::new();
            let mut par_on_f: Vec<DVec3> = Vec::new();
            let mut par_on_l: Vec<DVec3> = Vec::new();
            let mut map_seq_ver: DataMapOfShapeListOfShape = DataMapOfShapeListOfShape::new();
            let mut map_seq_par: DataMapOfShapeItem<Vec<DVec3>> = DataMapOfShapeItem::new();

            // OCCT L772-1081: for (ProfExp.Init(myProfile); ProfExp.More();
            // ProfExp.Next()).
            for prof_current in wire_edges(&self.my_profile.clone()) {
                //-----------------------------------------------
                // Return two faces separated by the bissectrice.
                //-----------------------------------------------
                // OCCT L777-778.
                let f0 = self
                    .my_map
                    .find(&s0)
                    .find(&prof_current)
                    .first()
                    .cloned()
                    .expect("myMap(S0)(Prof)");
                let f1 = self
                    .my_map
                    .find(&s1)
                    .find(&prof_current)
                    .first()
                    .cloned()
                    .expect("myMap(S1)(Prof)");

                //------------------------------------
                // Return parallel edges on each face.
                //------------------------------------
                // OCCT L783-790.
                let (vf, vl) = edge_vertices(&prof_current);

                let e0 = self
                    .my_map
                    .find(&s0)
                    .find(&vf)
                    .first()
                    .cloned()
                    .expect("myMap(S0)(VF)");
                let e1 = self
                    .my_map
                    .find(&s0)
                    .find(&vl)
                    .first()
                    .cloned()
                    .expect("myMap(S0)(VL)");
                let e2 = self
                    .my_map
                    .find(&s1)
                    .find(&vf)
                    .first()
                    .cloned()
                    .expect("myMap(S1)(VF)");
                let e3 = self
                    .my_map
                    .find(&s1)
                    .find(&vl)
                    .first()
                    .cloned()
                    .expect("myMap(S1)(VL)");

                // OCCT L792-803.
                let mut inv0 = [false; 2];
                let mut inv1 = [false; 2];
                if concave0 {
                    crate::brep_fill::brep_fill_evolved_d::is_inversed(&s0, &e0, &e1, &mut inv0);
                }
                if concave1 {
                    crate::brep_fill::brep_fill_evolved_d::is_inversed(&s1, &e2, &e3, &mut inv1);
                }

                //---------------------------------------------
                // Construction of geometries.
                //---------------------------------------------
                // OCCT L808.
                let trim = BRepFillTrimSurfaceTool::new(&bis, &f0, &f1, &e0, &e2, inv0[0], inv1[0]);

                //-----------------------------------------------------------
                // Construction of vertices corresponding to the node of the map
                //-----------------------------------------------------------
                // OCCT L812-824.
                let mut vs = Shape::null();
                let mut ve = Shape::null();

                let (node1_pre, node2) = if reverse {
                    (arc_second_node(&current_arc), arc_first_node(&current_arc))
                } else {
                    (arc_first_node(&current_arc), arc_second_node(&current_arc))
                };
                //--------------------------------------------------------
                // Particular case when the node is on a vertex of the spine.
                //--------------------------------------------------------
                // OCCT L828-839.
                let node1 = if node_on_basic_elt(&node1_pre) {
                    if s0.shape_type() == ShapeType::Vertex {
                        arc_first_node(&basic_elt_start_arc(&arc_first_element(&current_arc)))
                    } else if s1.shape_type() == ShapeType::Vertex {
                        arc_first_node(&basic_elt_start_arc(&arc_second_element(&current_arc)))
                    } else {
                        node1_pre
                    }
                } else {
                    node1_pre
                };
                // End of particular case.

                // OCCT L841-845.
                let start_on_f = crate::brep_fill::brep_fill_evolved_d::vertex_from_node(
                    &node1,
                    &prof_current,
                    &vf,
                    &vl,
                    &mut map_node_vertex,
                    &mut vs,
                );

                let end_on_f = crate::brep_fill::brep_fill_evolved_d::vertex_from_node(
                    &node2,
                    &prof_current,
                    &vf,
                    &vl,
                    &mut map_node_vertex,
                    &mut ve,
                );

                //-----------------------------------------------------------
                // Construction of vertices on edges parallel to the spine.
                //-----------------------------------------------------------
                // OCCT L850-881.
                if !map_seq_ver.is_bound(&vf) {
                    if inv0[0] || inv1[0] {
                        par_on_f.clear();
                        v_on_f.clear();
                    } else {
                        trim.intersect_with(&e0, &e2, &mut par_on_f);
                        v_on_f.clear();
                        for _s in 1..=par_on_f.len() {
                            let vc = builder_make_vertex();
                            v_on_f.push(vc);
                        }
                        if start_on_f == 1 {
                            v_on_f[0] = vs.clone();
                        }
                        if end_on_f == 1 {
                            let n = par_on_f.len();
                            v_on_f[n - 1] = ve.clone();
                        }
                    }
                } else {
                    par_on_f = map_seq_par.find(&vf).clone();
                    v_on_f = map_seq_ver.find(&vf).clone();
                }

                // OCCT L883-914.
                if !map_seq_ver.is_bound(&vl) {
                    if inv0[1] || inv1[1] {
                        par_on_l.clear();
                        v_on_l.clear();
                    } else {
                        trim.intersect_with(&e1, &e3, &mut par_on_l);
                        v_on_l.clear();
                        for _s in 1..=par_on_l.len() {
                            let vc = builder_make_vertex();
                            v_on_l.push(vc);
                        }
                        if start_on_f == 3 {
                            v_on_l[0] = vs.clone();
                        }
                        if end_on_f == 3 {
                            let n = par_on_l.len();
                            v_on_l[n - 1] = ve.clone();
                        }
                    }
                } else {
                    par_on_l = map_seq_par.find(&vl).clone();
                    v_on_l = map_seq_ver.find(&vl).clone();
                }

                //------------------------------------------------------
                // Test if the Bissectrice is not projected on the face
                //------------------------------------------------------
                // OCCT L919-930.
                if start_on_f == 0 && end_on_f == 0 && v_on_l.is_empty() && v_on_f.is_empty() {
                    // No trace of the bisectrice on the face.
                    continue;
                }

                if start_on_f == 0 && end_on_f == 0 && (v_on_l.len() + v_on_f.len() == 1) {
                    // the first or last node of the arc is on the edge
                    // but the arc is not on the face.
                    continue;
                }

                //---------------------------------------------------------
                // determine the intervals of the bissectrice that are
                // projected on F[0] and F[1].
                //---------------------------------------------------------
                // OCCT L936-950.
                let mut last_par: Vec<f64> = Vec::new();
                let mut first_par: Vec<f64> = Vec::new();
                let mut first_v: Vec<Shape> = Vec::new();
                let mut last_v: Vec<Shape> = Vec::new();

                crate::brep_fill::brep_fill_evolved_d::compute_intervals(
                    &v_on_f,
                    &v_on_l,
                    &par_on_f,
                    &par_on_l,
                    &trim,
                    &bis,
                    &vs,
                    &ve,
                    &mut first_par,
                    &mut last_par,
                    &mut first_v,
                    &mut last_v,
                );

                // OCCT L952-1010: for (Ti = 1; Ti <= FirstPar.Length(); Ti++).
                for ti in 1..=first_par.len() {
                    let mut v1 = first_v[ti - 1].clone();
                    let mut v2 = last_v[ti - 1].clone();

                    // OCCT L959: Trim.Project(FirstPar, LastPar, CBis,
                    // PCurve1, PCurve2, Continuity).
                    let (cbis, pcurve1, pcurve2, continuity) =
                        trim.project(first_par[ti - 1], last_par[ti - 1]);
                    let cbis: Curve3 = cbis.expect("Trim.Project Curve");
                    let (cbis_first, cbis_last) = {
                        let dom = CurveEval::default_domain(&cbis);
                        (dom[0], dom[1])
                    };

                    //-------------------------------------
                    // Coding of the edge.
                    //-------------------------------------
                    // OCCT L964: myBuilder.MakeEdge(CurrentEdge, CBis, tol).
                    let mut current_edge = crate::brep_fill::brep_fill_evolved_d::builder_make_edge_curve(
                        &cbis,
                        brep_fill_confusion(),
                    );

                    // OCCT L966-967.
                    builder_update_vertex_point_tol(
                        &mut v1,
                        CurveEval::point_at(&cbis, cbis_first),
                        brep_fill_confusion(),
                    );
                    builder_update_vertex_point_tol(
                        &mut v2,
                        CurveEval::point_at(&cbis, cbis_last),
                        brep_fill_confusion(),
                    );

                    // OCCT L969-970.
                    builder_add_edge_vertex(
                        &mut current_edge,
                        &shape_oriented(&v1, Orientation::Forward),
                    );
                    builder_add_edge_vertex(
                        &mut current_edge,
                        &shape_oriented(&v2, Orientation::Reversed),
                    );

                    // OCCT L972.
                    builder_range_edge(&mut current_edge, cbis_first, cbis_last);
                    // OCCT L973-974.
                    if let (Some(pc1), Some(pc2)) = (pcurve1.clone(), pcurve2.clone()) {
                        builder_update_edge_pcurve(
                            &mut current_edge,
                            &pc1,
                            &f0,
                            brep_fill_confusion(),
                        );
                        builder_update_edge_pcurve(
                            &mut current_edge,
                            &pc2,
                            &f1,
                            brep_fill_confusion(),
                        );
                    }

                    // OCCT L976.
                    crate::brep_fill::brep_fill_evolved::builder_continuity(
                        &current_edge,
                        &f0,
                        &f1,
                        continuity,
                    );

                    //-------------------------------------------
                    // Storage of the edge for each of faces.
                    //-------------------------------------------
                    // OCCT L981-987.
                    for k in 0..=1 {
                        let fk = if k == 0 { &f0 } else { &f1 };
                        if !map_bis.is_bound(fk) {
                            map_bis.bind(fk, Vec::new());
                        }
                    }
                    //---------------------------------------------------------------
                    // orientation of the edge depends on the direction of the skin.
                    // skin => same orientation E[0] , inverted orientation E[2]
                    // if contreskin it is inverted.
                    //--------------------------------------------------------------
                    // OCCT L993-994.
                    let e0_ori = crate::brep_fill::brep_fill_evolved_d::brep_tools_ori_edge_in_face(&e0, &f0);
                    let e0 = shape_oriented(&e0, e0_ori);
                    let e2_ori = crate::brep_fill::brep_fill_evolved_d::brep_tools_ori_edge_in_face(&e2, &f1);
                    let e2 = shape_oriented(&e2, e2_ori);

                    // OCCT L996-1009.
                    if crate::brep_fill::brep_fill_evolved_d::distance_to_oz(&vf)
                        < crate::brep_fill::brep_fill_evolved_d::distance_to_oz(&vl)
                    {
                        // Skin
                        let ori = e0.orientation;
                        map_bis
                            .find_mut(&f0)
                            .push(shape_oriented(&current_edge, ori));
                        let complement = top_abs_reverse(e2.orientation);
                        current_edge = shape_oriented(&current_edge, complement);
                        map_bis.find_mut(&f1).push(current_edge.clone());
                    } else {
                        // Contreskin
                        let ori = e2.orientation;
                        map_bis
                            .find_mut(&f1)
                            .push(shape_oriented(&current_edge, ori));
                        let complement = top_abs_reverse(e0.orientation);
                        current_edge = shape_oriented(&current_edge, complement);
                        map_bis.find_mut(&f0).push(current_edge.clone());
                    }
                }

                //----------------------------------------------
                // Storage of vertices on parallel edges.
                // fill MapBis and MapVerPar.
                // VOnF for E[0] and E[2].
                // VOnL for E[1] and E[3].
                //----------------------------------------------
                // OCCT L1018-1043.
                let mut k: i32 = 0;
                while k <= 2 {
                    if !map_seq_ver.is_bound(&vf) && !v_on_f.is_empty() {
                        let ek = if k == 0 { &e0 } else { &e2 };
                        if !map_bis.is_bound(ek) {
                            map_bis.bind(ek, Vec::new());
                            map_ver_par.bind(ek, Vec::new());
                        }
                        for ii in 1..=v_on_f.len() {
                            map_bis.find_mut(ek).push(v_on_f[ii - 1].clone());
                            if k == 0 {
                                map_ver_par.find_mut(ek).push(par_on_f[ii - 1].y);
                            } else {
                                map_ver_par.find_mut(ek).push(par_on_f[ii - 1].z);
                            }
                        }
                    }
                    k += 2;
                }

                // OCCT L1045-1070.
                let mut k: i32 = 1;
                while k <= 3 {
                    if !map_seq_ver.is_bound(&vl) && !v_on_l.is_empty() {
                        let ek = if k == 1 { &e1 } else { &e3 };
                        if !map_bis.is_bound(ek) {
                            map_bis.bind(ek, Vec::new());
                            map_ver_par.bind(ek, Vec::new());
                        }
                        for ii in 1..=v_on_l.len() {
                            map_bis.find_mut(ek).push(v_on_l[ii - 1].clone());
                            if k == 1 {
                                map_ver_par.find_mut(ek).push(par_on_l[ii - 1].y);
                            } else {
                                map_ver_par.find_mut(ek).push(par_on_l[ii - 1].z);
                            }
                        }
                    }
                    k += 2;
                }

                //----------------------------------------------------------------
                // Edge [1] of the current face will be Edge [0] of the next face.
                // => copy of VonL in VonF. To avoid creating the same vertices twice.
                //-----------------------------------------------------------------
                // OCCT L1077-1080 (the NCollection Bind copies the
                // sequences — the clone mirror).
                map_seq_par.bind(&vf, par_on_f.clone());
                map_seq_ver.bind(&vf, v_on_f.clone());
                map_seq_par.bind(&vl, par_on_l.clone());
                map_seq_ver.bind(&vl, v_on_l.clone());
            }
        }

        //----------------------------------
        // Construction of parallel edges.
        //----------------------------------
        // OCCT L1087-1190.
        let mut prec_prof = Shape::null();
        let mut current_prof = Shape::null();

        let spine_keys: Vec<Shape> = self.my_map.iter().map(|(ks, _)| ks.clone()).collect();
        for current_spine in spine_keys {
            for prof in wire_edges(&self.my_profile.clone()) {
                current_prof = prof;
                let (vcf, _vcl) = edge_vertices(&current_prof);
                let current_edge = self
                    .my_map
                    .find(&current_spine)
                    .find(&vcf)
                    .first()
                    .cloned()
                    .expect("myMap(Spine)(VCF)");

                //-------------------------------------------------------------
                // RQ : Current Edge is oriented relatively to the face (oriented forward)
                //     generated by edge CurrentProf .
                //-------------------------------------------------------------
                if map_bis.is_bound(&current_edge) {
                    //--------------------------------------------------------
                    // Find if one of two faces connected to the edge
                    // belongs to volevo. The edges on this face serve
                    // to eliminate certain vertices that can appear twice
                    // on the parallel edge. These Vertices correspond to the
                    // nodes of the map.
                    //---------------------------------------------------------
                    let mut face_controle = Shape::null();
                    let mut ya_face = true;

                    face_controle = self
                        .my_map
                        .find(&current_spine)
                        .find(&current_prof)
                        .first()
                        .cloned()
                        .expect("myMap(Spine)(Prof)");
                    if !map_bis.is_bound(&face_controle) {
                        ya_face = false;
                        if !prec_prof.is_null() {
                            face_controle = self
                                .my_map
                                .find(&current_spine)
                                .find(&prec_prof)
                                .first()
                                .cloned()
                                .expect("myMap(Spine)(PrecProf)");
                            if map_bis.is_bound(&face_controle) {
                                ya_face = true;
                            }
                        }
                    }

                    if ya_face {
                        //------------------------------------------------------------
                        // No connected face in the volevo => no parallel edge.
                        //------------------------------------------------------------
                        let mut a_seq_of_shape: Vec<Shape> = Vec::new();
                        let edges_controle = map_bis.find(&face_controle).clone();
                        crate::brep_fill::brep_fill_evolved_d::trim_edge(
                            &current_edge,
                            &edges_controle,
                            map_bis.find_mut(&current_edge),
                            map_ver_par.find_mut(&current_edge),
                            &mut a_seq_of_shape,
                        );

                        for k in 1..=a_seq_of_shape.len() {
                            self.my_map
                                .find_mut(&current_spine)
                                .find_mut(&vcf)
                                .push(a_seq_of_shape[k - 1].clone());
                        }
                    }
                }
                prec_prof = current_prof.clone();
            }

            //------------------------------------------------------------
            // Construction of the parallel edge from the last vertex of myProfile.
            //------------------------------------------------------------
            // OCCT L1161-1189.
            let current_prof_last = current_prof.clone();
            let (_vcf, vcl) = edge_vertices(&current_prof_last);
            let current_edge = self
                .my_map
                .find(&current_spine)
                .find(&vcl)
                .first()
                .cloned()
                .expect("myMap(Spine)(VCL)");

            if map_bis.is_bound(&current_edge) {
                let mut ya_face = true;
                let mut face_controle = Shape::null();

                face_controle = self
                    .my_map
                    .find(&current_spine)
                    .find(&current_prof_last)
                    .first()
                    .cloned()
                    .expect("myMap(Spine)(Prof)");
                if !map_bis.is_bound(&face_controle) {
                    ya_face = false;
                }
                // the number of element of the list allows to know
                // if the edges have already been done (closed profile) .
                if ya_face && self.my_map.find(&current_spine).find(&vcl).len() <= 1 {
                    let mut a_seq_of_shape: Vec<Shape> = Vec::new();
                    let edges_controle = map_bis.find(&face_controle).clone();
                    crate::brep_fill::brep_fill_evolved_d::trim_edge(
                        &current_edge,
                        &edges_controle,
                        map_bis.find_mut(&current_edge),
                        map_ver_par.find_mut(&current_edge),
                        &mut a_seq_of_shape,
                    );

                    for k in 1..=a_seq_of_shape.len() {
                        self.my_map
                            .find_mut(&current_spine)
                            .find_mut(&vcl)
                            .push(a_seq_of_shape[k - 1].clone());
                    }
                }
            }
        }

        //-------------------------------------------------------------------
        // Cut faces by edges.
        //-------------------------------------------------------------------
        // OCCT L1195-1261.
        let spine_keys: Vec<Shape> = self.my_map.iter().map(|(ks, _)| ks.clone()).collect();
        for current_spine in spine_keys {
            for current_prof in wire_edges(&self.my_profile.clone()) {
                let current_face = self
                    .my_map
                    .find(&current_spine)
                    .find(&current_prof)
                    .first()
                    .cloned()
                    .expect("myMap(Spine)(Prof)");
                self.my_map
                    .find_mut(&current_spine)
                    .find_mut(&current_prof)
                    .clear();

                if map_bis.is_bound(&current_face) {
                    //----------------------------------------------------------
                    // If the face does not contain edges that can limit it
                    // it does not appear in volevo.
                    // cut of face by edges can generate many faces.
                    //
                    // Add edges generated on the edges parallel to the set
                    // of edges that limit the face.
                    //
                    //------------------------------------------------------------
                    let (vcf, vcl) = edge_vertices(&current_prof);

                    let lf = self.my_map.find(&current_spine).find(&vcf).clone();

                    let ori = crate::brep_fill::brep_fill_evolved_d::brep_tools_ori_edge_in_face(
                        &lf.first().cloned().expect("LF.First"),
                        &current_face,
                    );
                    for itl in lf.iter().skip(1) {
                        let re = itl.clone();
                        map_bis.find_mut(&current_face).push(shape_oriented(&re, ori));
                    }
                    let ll = self.my_map.find(&current_spine).find(&vcl).clone();
                    let ori = crate::brep_fill::brep_fill_evolved_d::brep_tools_ori_edge_in_face(
                        &ll.first().cloned().expect("LL.First"),
                        &current_face,
                    );
                    for itl in ll.iter().skip(1) {
                        let re = itl.clone();
                        map_bis.find_mut(&current_face).push(shape_oriented(&re, ori));
                    }

                    // Cut of the face.
                    let mut a_seq_of_shape: Vec<Shape> = Vec::new();

                    crate::brep_fill::brep_fill_evolved_d::trim_face(
                        &current_face,
                        map_bis.find_mut(&current_face),
                        &mut a_seq_of_shape,
                    );

                    for ii in 1..=a_seq_of_shape.len() {
                        builder_add_compound_shape(&mut self.my_shape, &a_seq_of_shape[ii - 1]);
                        self.my_map
                            .find_mut(&current_spine)
                            .find_mut(&current_prof)
                            .push(a_seq_of_shape[ii - 1].clone());
                    }
                }
            }
            //-----------------------------------------------------------------
            // Removal of first edge (edge of origin) from lists of myMap
            // corresponding to vertices of the profile.
            //-----------------------------------------------------------------
            // OCCT L1251-1260.
            let mut vmap: std::collections::HashSet<ShapeKey> = std::collections::HashSet::new();
            for explo_current in crate::brep_algo::tool::explorer(
                &self.my_profile.clone(),
                ShapeType::Vertex,
                ShapeType::Shape,
            ) {
                if vmap.insert(shape_key(&explo_current)) {
                    // myMap(CurrentSpine)(Explo.Current()).RemoveFirst().
                    let list = self.my_map.find_mut(&current_spine).find_mut(&explo_current);
                    if !list.is_empty() {
                        list.remove(0);
                    }
                }
            }
        }
        self.my_is_done = true;
    }
}
