//! Precision constants and per-entity tolerance query helpers.
//!
//! Analogous to OCCT's `Precision` class and `BRep_Builder::UpdateVertex` /
//! `BRep_Builder::UpdateEdge` tolerance API.
//!
//! # Design
//!
//! OCCT stores a per-entity tolerance on each `BRep_Vertex`, `BRep_Edge`, and
//! `BRep_Face`.  These tolerances represent the maximum deviation between the
//! ideal (analytic) geometry and the actual model, arising from tessellation,
//! import rounding, or algorithm approximations.
//!
//! RCAD stores the same data in `GeomStore` as parallel `Vec<f64>` arrays
//! (`vertex_tolerance`, `edge_tolerance`, `face_tolerance`), indexed the same
//! way as the corresponding topology arrays.  When a tolerance is absent or
//! zero the query functions fall back to the `CONFUSION` constant.
//!
//! # Usage
//!
//! ```rust
//! use rcad_kernel::{vertex_tolerance, edge_tolerance, CONFUSION};
//!
//! // brep with no stored tolerances → default confusion value
//! let brep = rcad_kernel::BRep::new();
//! assert_eq!(vertex_tolerance(&brep, 0), CONFUSION);
//! ```

use crate::BRep;
use crate::geom::{Curve2dEval, CurveEval, SurfaceEval};

// ── Precision constants ───────────────────────────────────────────────────────

/// Point-coincidence tolerance.
/// Analogous to `Precision::Confusion()` = 1e-7 in OCCT.
pub const CONFUSION: f64 = 1e-7;

/// Angular tolerance (radians).
/// Analogous to `Precision::Angular()` = 1e-12 in OCCT.
pub const ANGULAR: f64 = 1e-12;

/// Tessellation / approximation tolerance.
/// Analogous to `Precision::Approximation()` = 1e-4 in OCCT.
pub const APPROXIMATION: f64 = 1e-4;

// ── Per-entity tolerance queries ──────────────────────────────────────────────

/// Tolerance of vertex `vertex_idx`.
///
/// Returns the stored value when positive, otherwise `CONFUSION`.
/// Analogous to `BRep_Tool::Tolerance(vertex)` in OCCT.
pub fn vertex_tolerance(brep: &BRep, vertex_idx: usize) -> f64 {
    brep.geom
        .vertex_tolerance
        .get(vertex_idx)
        .copied()
        .filter(|&t| t > 0.0)
        .unwrap_or(CONFUSION)
}

/// Tolerance of edge `edge_idx`.
///
/// Returns the stored value when positive, otherwise `CONFUSION`.
/// Analogous to `BRep_Tool::Tolerance(edge)` in OCCT.
pub fn edge_tolerance(brep: &BRep, edge_idx: usize) -> f64 {
    brep.geom
        .edge_tolerance
        .get(edge_idx)
        .copied()
        .filter(|&t| t > 0.0)
        .unwrap_or(CONFUSION)
}

/// Tolerance of face `face_flat_idx` (flattened index across all solids/shells,
/// same ordering as `GeomStore.face_surface`).
///
/// Returns the stored value when positive, otherwise `CONFUSION`.
/// Analogous to `BRep_Tool::Tolerance(face)` in OCCT.
pub fn face_tolerance(brep: &BRep, face_flat_idx: usize) -> f64 {
    brep.geom
        .face_tolerance
        .get(face_flat_idx)
        .copied()
        .filter(|&t| t > 0.0)
        .unwrap_or(CONFUSION)
}

/// Maximum tolerance over all entities with explicitly stored values.
///
/// Returns `CONFUSION` when no tolerances are stored.
/// Analogous to `BRep_Builder::UpdateVertex` accumulated maximum in OCCT.
pub fn model_tolerance(brep: &BRep) -> f64 {
    brep.geom
        .vertex_tolerance
        .iter()
        .chain(brep.geom.edge_tolerance.iter())
        .chain(brep.geom.face_tolerance.iter())
        .copied()
        .fold(CONFUSION, f64::max)
}

/// Effective surface parameter domain [u1, u2, v1, v2] for a face.
///
/// Uses `GeomStore.face_surface_range` if set; otherwise falls back to
/// `SurfaceEval::default_domain()` of the underlying surface.
/// Analogous to `BRep_Face::UVBounds()` in OCCT.
pub fn face_domain(brep: &BRep, face_flat_idx: usize) -> [f64; 4] {
    if let Some(Some(range)) = brep.geom.face_surface_range.get(face_flat_idx) {
        return *range;
    }
    if let Some(Some(surf_idx)) = brep.geom.face_surface.get(face_flat_idx)
        && let Some(surf) = brep.geom.surfaces.get(*surf_idx)
    {
        return surf.default_domain();
    }
    [0.0, 1.0, 0.0, 1.0]
}

/// SameParameter flag for edge `edge_idx`.
///
/// Returns the stored value when present, otherwise `true`
/// (all analytic primitives generated by RCAD are same-parameter by construction).
/// Analogous to `BRep_Edge::SameParameter()` in OCCT.
pub fn edge_same_parameter(brep: &BRep, edge_idx: usize) -> bool {
    brep.geom
        .edge_same_parameter
        .get(edge_idx)
        .copied()
        .unwrap_or(true)
}

/// SameRange flag for edge `edge_idx`.
///
/// Returns the stored value when present, otherwise `true`
/// (all analytic primitives generated by RCAD are same-range by construction).
/// Analogous to `BRep_Edge::SameRange()` in OCCT.
pub fn edge_same_range(brep: &BRep, edge_idx: usize) -> bool {
    brep.geom
        .edge_same_range
        .get(edge_idx)
        .copied()
        .unwrap_or(true)
}

// ── Write / mutator API ───────────────────────────────────────────────────────
//
// These functions are the Rust equivalents of OCCT's
// `BRep_Builder::UpdateVertex`, `BRep_Builder::UpdateEdge`, and
// `BRep_Builder::UpdateFace`.  They extend the `GeomStore` tolerance arrays
// on demand so callers do not need to pre-size them.

/// Ensure all three tolerance arrays in `brep.geom` are sized to cover every
/// entity currently in the `BRep`.  Newly extended slots are filled with
/// `CONFUSION` (the global precision floor).
///
/// Analogous to the internal resize step inside `BRep_Builder::UpdateVertex`.
pub fn resize_tolerance_arrays(brep: &mut BRep) {
    let nv = brep.vertices.len();
    let ne = brep.edges.len();
    let nf: usize = brep.solids.iter()
        .flat_map(|s| s.shells.iter())
        .map(|sh| sh.faces.len())
        .sum();

    if brep.geom.vertex_tolerance.len() < nv {
        brep.geom.vertex_tolerance.resize(nv, CONFUSION);
    }
    if brep.geom.edge_tolerance.len() < ne {
        brep.geom.edge_tolerance.resize(ne, CONFUSION);
    }
    if brep.geom.face_tolerance.len() < nf {
        brep.geom.face_tolerance.resize(nf, CONFUSION);
    }
}

/// Set the tolerance of vertex `vi` to exactly `tol`.
///
/// Extends the `vertex_tolerance` array if necessary.
/// Clamps `tol` to `CONFUSION` minimum.
///
/// Analogous to `BRep_Builder::UpdateVertex(V, tol)` (absolute form).
pub fn set_vertex_tolerance(brep: &mut BRep, vi: usize, tol: f64) {
    let t = tol.max(CONFUSION);
    if brep.geom.vertex_tolerance.len() <= vi {
        brep.geom.vertex_tolerance.resize(vi + 1, CONFUSION);
    }
    brep.geom.vertex_tolerance[vi] = t;
}

/// Raise the tolerance of vertex `vi` to at least `tol`.
///
/// Uses `max(current, tol)` — never lowers an existing tolerance.
/// Extends the array on demand.
/// Analogous to `BRep_Builder::UpdateVertex(V, tol)` in OCCT.
pub fn update_vertex_tolerance(brep: &mut BRep, vi: usize, tol: f64) {
    let t = tol.max(CONFUSION);
    if brep.geom.vertex_tolerance.len() <= vi {
        brep.geom.vertex_tolerance.resize(vi + 1, CONFUSION);
    }
    let cur = &mut brep.geom.vertex_tolerance[vi];
    if t > *cur {
        *cur = t;
    }
}

/// Set the tolerance of edge `ei` to exactly `tol`.
///
/// Extends the `edge_tolerance` array if necessary.
/// Analogous to `BRep_Builder::UpdateEdge(E, tol)` (absolute form).
pub fn set_edge_tolerance(brep: &mut BRep, ei: usize, tol: f64) {
    let t = tol.max(CONFUSION);
    if brep.geom.edge_tolerance.len() <= ei {
        brep.geom.edge_tolerance.resize(ei + 1, CONFUSION);
    }
    brep.geom.edge_tolerance[ei] = t;
}

/// Raise the tolerance of edge `ei` to at least `tol`.
///
/// Uses `max(current, tol)` — never lowers.
/// Analogous to `BRep_Builder::UpdateEdge(E, tol)` in OCCT.
pub fn update_edge_tolerance(brep: &mut BRep, ei: usize, tol: f64) {
    let t = tol.max(CONFUSION);
    if brep.geom.edge_tolerance.len() <= ei {
        brep.geom.edge_tolerance.resize(ei + 1, CONFUSION);
    }
    let cur = &mut brep.geom.edge_tolerance[ei];
    if t > *cur {
        *cur = t;
    }
}

/// Set the tolerance of face `fi` (flat index) to exactly `tol`.
///
/// Extends the `face_tolerance` array if necessary.
/// Analogous to `BRep_Builder::UpdateFace(F, tol)` (absolute form).
pub fn set_face_tolerance(brep: &mut BRep, fi: usize, tol: f64) {
    let t = tol.max(CONFUSION);
    if brep.geom.face_tolerance.len() <= fi {
        brep.geom.face_tolerance.resize(fi + 1, CONFUSION);
    }
    brep.geom.face_tolerance[fi] = t;
}

/// Raise the tolerance of face `fi` (flat index) to at least `tol`.
///
/// Uses `max(current, tol)` — never lowers.
/// Analogous to `BRep_Builder::UpdateFace(F, tol)` in OCCT.
pub fn update_face_tolerance(brep: &mut BRep, fi: usize, tol: f64) {
    let t = tol.max(CONFUSION);
    if brep.geom.face_tolerance.len() <= fi {
        brep.geom.face_tolerance.resize(fi + 1, CONFUSION);
    }
    let cur = &mut brep.geom.face_tolerance[fi];
    if t > *cur {
        *cur = t;
    }
}

/// Enforce the tolerance hierarchy **in-place**:
///
/// ```text
///   vertex_tol ≥ edge_tol ≥ face_tol
/// ```
///
/// Specifically:
///
/// 1. For each edge: `edge_tol = max(edge_tol, face_tol(all adjacent faces))`.
/// 2. For each vertex: `vertex_tol = max(vertex_tol, edge_tol(all adjacent edges))`.
///
/// This ensures the "wider" entity (vertex) always carries at least as much
/// tolerance as the narrower entities it bounds — the same invariant OCCT
/// maintains via `BRepLib::UpdateEdgeTol` and `BRep_Builder::UpdateVertex`.
///
/// Call `resize_tolerance_arrays` first if the arrays may not be populated.
pub fn finalize_tolerance_hierarchy(brep: &mut BRep) {
    resize_tolerance_arrays(brep);

    // Step 1: face → edge.
    // Build edge → max(adjacent face tolerance).
    let mut edge_from_face: Vec<f64> = vec![CONFUSION; brep.edges.len()];
    let mut flat_fi = 0usize;
    for solid in &brep.solids {
        for shell in &solid.shells {
            for face in &shell.faces {
                let ftol = brep.geom.face_tolerance
                    .get(flat_fi)
                    .copied()
                    .unwrap_or(CONFUSION);
                for we in &face.outer_wire.edges {
                    if we.idx < edge_from_face.len() {
                        edge_from_face[we.idx] = edge_from_face[we.idx].max(ftol);
                    }
                }
                for iw in &face.inner_wires {
                    for we in &iw.edges {
                        if we.idx < edge_from_face.len() {
                            edge_from_face[we.idx] = edge_from_face[we.idx].max(ftol);
                        }
                    }
                }
                flat_fi += 1;
            }
        }
    }
    for (ei, &ftol) in edge_from_face.iter().enumerate() {
        if let Some(etol) = brep.geom.edge_tolerance.get_mut(ei)
            && ftol > *etol {
                *etol = ftol;
            }
    }

    // Step 2: edge → vertex.
    let ne = brep.edges.len();
    for ei in 0..ne {
        let etol = brep.geom.edge_tolerance.get(ei).copied().unwrap_or(CONFUSION);
        let st = brep.edges[ei].start;
        let en = brep.edges[ei].end;
        if let Some(vtol) = brep.geom.vertex_tolerance.get_mut(st)
            && etol > *vtol {
                *vtol = etol;
            }
        if let Some(vtol) = brep.geom.vertex_tolerance.get_mut(en)
            && etol > *vtol {
                *vtol = etol;
            }
    }
}

/// Part A: OCCT `BRepLib::SameParameter` equivalent.
///
/// For each edge that has a 3D curve and at least one pcurve, sample the
/// deviation between `curve(t)` and `surface(u(t), v(t))` at `samples_per_edge`
/// points.  Update the edge tolerance to `max(current, max_deviation)`.
///
/// Edges without a 3D curve, without pcurves, or without a parametric range
/// are skipped.
pub fn brep_same_parameter(brep: &mut BRep, samples_per_edge: usize) {
    let samples = samples_per_edge.max(2);
    for ei in 0..brep.edges.len() {
        // Get 3D curve
        let Some(curve_idx) = brep.geom.edge_curve.get(ei).copied().flatten() else {
            continue;
        };
        let Some(curve) = brep.geom.curves.get(curve_idx) else {
            continue;
        };
        // Get parametric range
        let Some([t1, t2]) = brep.geom.edge_curve_range.get(ei).copied().flatten() else {
            continue;
        };
        if (t2 - t1).abs() < 1e-15 {
            continue;
        }
        // Get pcurves
        let Some(pcurves) = brep.geom.edge_pcurves.get(ei) else {
            continue;
        };
        if pcurves.is_empty() {
            continue;
        }

        let mut max_dev = 0.0_f64;
        for pc in pcurves {
            let Some(surface) = brep.geom.surfaces.get(pc.surface_idx) else {
                continue;
            };
            let Some(pc_curve) = brep.geom.curve2ds.get(pc.curve2d_idx) else {
                continue;
            };

            for si in 0..samples {
                let t = t1 + (t2 - t1) * si as f64 / (samples - 1) as f64;
                let uv = pc_curve.point_at(t);
                let p_surface = surface.point_at(uv.x, uv.y);
                let p_curve = curve.point_at(t);
                let dev = (p_surface - p_curve).length();
                if dev > max_dev {
                    max_dev = dev;
                }
            }
        }

        if max_dev > 0.0 {
            crate::tolerance::set_edge_tolerance(brep, ei, max_dev);
        }
    }
}

/// Part B: Compute per-vertex tolerance from distance to adjacent edges.
///
/// For each vertex, find all adjacent edges and compute the minimum distance
/// from the vertex to each edge's 3D curve (sampled).  Update vertex tolerance
/// via `update_vertex_tolerance(brep, vi, max_dist)`.
///
/// Edges without 3D curves fall back to half the edge length as a heuristic.
pub fn compute_vertex_tolerances(brep: &mut BRep) {
    use crate::topo_query::vertex_adjacent_edges;

    for vi in 0..brep.vertices.len() {
        let v_pos = brep.vertices[vi].point;
        let adj_edges = vertex_adjacent_edges(brep, vi);
        if adj_edges.is_empty() {
            continue;
        }

        let mut max_dist = 0.0_f64;
        for &ei in &adj_edges {
            let Some(edge) = brep.edges.get(ei) else { continue; };
            let other_vi = if edge.start == vi { edge.end } else { edge.start };
            let Some(other) = brep.vertices.get(other_vi) else { continue; };
            let edge_len = (other.point - v_pos).length();

            // Prefer 3D curve distance over edge-length fallback
            if let Some(curve_idx) = brep.geom.edge_curve.get(ei).copied().flatten() {
                if let Some(curve) = brep.geom.curves.get(curve_idx) {
                    if let Some([t1, t2]) = brep.geom.edge_curve_range.get(ei).copied().flatten() {
                        let mut min_dist = f64::MAX;
                        for s in 0..20 {
                            let t = t1 + (t2 - t1) * s as f64 / 19.0;
                            let pt = curve.point_at(t);
                            let d = (pt - v_pos).length();
                            if d < min_dist { min_dist = d; }
                        }
                        if min_dist < f64::MAX && min_dist > max_dist {
                            max_dist = min_dist;
                        }
                        continue; // used curve distance, skip edge-length fallback
                    }
                }
            }
            // Fallback: half edge length
            let half = edge_len * 0.5;
            if half > max_dist { max_dist = half; }
        }

        if max_dist > 0.0 {
            crate::tolerance::update_vertex_tolerance(brep, vi, max_dist);
        }
    }
}

/// ✅ OCCT对齐: CorrectTolerances — 统一后处理,等价于 OCCT boolean 后的
///    BRepLib::SameParameter + 逐顶点公差计算 + 层级传播 (finalize_tolerance_hierarchy).
///
/// 调用顺序:
/// 1. `resize_tolerance_arrays` — 确保所有容差数组长度正确
/// 2. `brep_same_parameter` — 从 3D/pcurve 偏差计算边公差
/// 3. `compute_vertex_tolerances` — 从相邻边距离计算顶点公差
/// 4. `finalize_tolerance_hierarchy` — 传播(面→边→顶点)确保层级一致
///
/// # Arguments
///
/// * `brep` - The BRep to correct tolerances on.
/// * `samples_per_edge` - Sample points per edge for deviation computation (min 2).
pub fn correct_tolerances(brep: &mut BRep, samples_per_edge: usize) {
    resize_tolerance_arrays(brep);
    brep_same_parameter(brep, samples_per_edge);
    compute_vertex_tolerances(brep);
    finalize_tolerance_hierarchy(brep);
}

/// ✅ OCCT对齐: SameRange — 确保每条边的 pcurve 范围和 edge_curve_range 一致。
///    OCCT BRepLib::SameRange 将 pcurve 的 range 调整为与 3D curve range 匹配。
///
/// 对每条边,如果 3D curve range 和 pcurve range 都已设置但不同,
/// 延长 pcurve range 到覆盖 3D curve range。
pub fn same_range(brep: &mut BRep) {
    for ei in 0..brep.edges.len() {
        let Some([t1, t2]) = brep.geom.edge_curve_range.get(ei).copied().flatten() else {
            continue;
        };
        if (t2 - t1).abs() < 1e-15 {
            continue;
        }
        let Some(pcurves) = brep.geom.edge_pcurves.get(ei) else {
            continue;
        };
        for pc in pcurves {
            let Some(pc_range) = brep.geom.curve2d_range.get(pc.curve2d_idx).copied().flatten() else {
                continue;
            };
            let (pc_t1, pc_t2) = (pc_range[0], pc_range[1]);
            let new_pc_t1 = pc_t1.min(t1);
            let new_pc_t2 = pc_t2.max(t2);
            if (new_pc_t1 - pc_t1).abs() > 1e-15 || (new_pc_t2 - pc_t2).abs() > 1e-15 {
                if let Some(range) = brep.geom.curve2d_range.get_mut(pc.curve2d_idx) {
                    *range = Some([new_pc_t1, new_pc_t2]);
                }
            }
        }
        // Mark as same range
        while brep.geom.edge_same_range.len() <= ei {
            brep.geom.edge_same_range.push(true);
        }
        brep.geom.edge_same_range[ei] = true;
    }
}

// ── BRep_Tool 等查询函数 ─────────────────────────────────────────────────────────

/// ✅ OCCT对齐: BRep_Tool::Curve(edge) — 返回边的 3D 曲线。
pub fn edge_curve<'a>(brep: &'a BRep, ei: usize) -> Option<&'a crate::geom::Curve3> {
    let ci = brep.geom.edge_curve.get(ei).copied().flatten()?;
    brep.geom.curves.get(ci)
}

/// ✅ OCCT对齐: BRep_Tool::Surface(face) — 返回面的曲面。
pub fn face_surface<'a>(brep: &'a BRep, face_flat_idx: usize) -> Option<&'a crate::geom::Surface3> {
    let si = brep.geom.face_surface.get(face_flat_idx).copied().flatten()?;
    brep.geom.surfaces.get(si)
}

/// ✅ OCCT对齐: BRep_Tool::PCurve(edge, face) — 返回边在面上的 pcurve。
pub fn edge_pcurve_on_face<'a>(brep: &'a BRep, ei: usize, face_flat_idx: usize) -> Option<&'a crate::geom::Curve2d> {
    let pcurves = brep.geom.edge_pcurves.get(ei)?;
    let pc = pcurves.iter().find(|pc| pc.surface_idx == face_flat_idx)?;
    let ci = pc.curve2d_idx;
    brep.geom.curve2ds.get(ci)
}

/// ✅ OCCT对齐: BRep_Tool::Degenerated(edge) — 边是否为退化边。
pub fn edge_is_degenerated(brep: &BRep, ei: usize) -> bool {
    brep.geom.edge_degenerated.get(ei).copied().unwrap_or(false)
}

/// ✅ OCCT对齐: BRep_Tool::SameParameter(edge) — 边是否 same-parameter。
pub fn edge_is_same_parameter(brep: &BRep, ei: usize) -> bool {
    brep.geom.edge_same_parameter.get(ei).copied().unwrap_or(true)
}

/// ✅ OCCT对齐: BRep_Tool::SameRange(edge) — 边是否 same-range。
pub fn edge_is_same_range(brep: &BRep, ei: usize) -> bool {
    brep.geom.edge_same_range.get(ei).copied().unwrap_or(true)
}

// ── CorrectCurveOnSurface / CorrectPointOnCurve ────────────────────────────────

/// ✅ OCCT对齐: BOPTools_AlgoTools::CorrectCurveOnSurface.
///
/// 对每条边，检查 pcurve(s) 和 3D 曲线之间的偏差。
/// 如果偏差超出边公差，膨胀边公差以覆盖偏差量。
/// 不修改 pcurve 曲线本身（当前实现只调公差，不调几何）。
///
/// 与 brep_same_parameter 的区别：
/// - brep_same_parameter: 采样偏差 → 更新边公差
/// - correct_curve_on_surface: 采样偏差 → 若超过边公差则膨胀
///
/// 效果类似，但后者是对 "已设置的公差不够" 的补正。
///
/// # Arguments
///
/// * `brep` - The BRep to correct.
/// * `samples_per_edge` - Sample points per edge.
pub fn correct_curve_on_surface(brep: &mut BRep, samples_per_edge: usize) {
    let n = samples_per_edge.max(2);
    // First pass: compute max deviation per edge (immutable borrow only).
    let deviations: Vec<(usize, f64)> = {
        let curves = &brep.geom.curves;
        let surfaces = &brep.geom.surfaces;
        let curve2ds = &brep.geom.curve2ds;
        (0..brep.edges.len()).filter_map(|ei| {
            let ci = brep.geom.edge_curve.get(ei).copied().flatten()?;
            let curve = curves.get(ci)?;
            let [t1, t2] = brep.geom.edge_curve_range.get(ei).copied().flatten()?;
            if (t2 - t1).abs() < 1e-15 { return None; }
            let pcurves = brep.geom.edge_pcurves.get(ei)?;
            if pcurves.is_empty() { return None; }
            let etol = edge_tolerance(brep, ei);

            let mut max_dev = 0.0_f64;
            for pc in pcurves {
                let surface = surfaces.get(pc.surface_idx)?;
                let pc_curve = curve2ds.get(pc.curve2d_idx)?;
                for si in 0..n {
                    let t = t1 + (t2 - t1) * si as f64 / (n - 1) as f64;
                    let uv = pc_curve.point_at(t);
                    let p_surf = surface.point_at(uv.x, uv.y);
                    let p_curve = curve.point_at(t);
                    let dev = (p_surf - p_curve).length();
                    if dev > max_dev { max_dev = dev; }
                }
            }
            if max_dev > etol { Some((ei, max_dev)) } else { None }
        }).collect()
    };
    // Second pass: apply tolerance updates (mutable borrow).
    for (ei, tol) in deviations {
        update_edge_tolerance(brep, ei, tol);
    }
}

/// ✅ OCCT对齐: BOPTools_AlgoTools::CorrectPointOnCurve.
///
/// 对每条边，检查顶点的 3D 位置到边曲线的距离。
/// 如果距离超出顶点公差，膨胀顶点公差。
pub fn correct_point_on_curve(brep: &mut BRep) {
    // Collect (vi, min_dist) pairs first, then apply — avoids borrow conflicts.
    let mut updates: Vec<(usize, f64)> = Vec::new();
    for ei in 0..brep.edges.len() {
        let curve = edge_curve(brep, ei).cloned();
        let Some(ref curve) = curve else { continue; };
        let Some([t1, t2]) = brep.geom.edge_curve_range.get(ei).copied().flatten() else { continue; };
        if (t2 - t1).abs() < 1e-15 { continue; }
        for &vi in &[brep.edges[ei].start, brep.edges[ei].end] {
            let Some(vp) = brep.vertices.get(vi).map(|v| v.point) else { continue; };
            let mut min_dist = f64::MAX;
            for s in 0..20 {
                let t = t1 + (t2 - t1) * s as f64 / 19.0;
                let pt = curve.point_at(t);
                let d = (pt - vp).length();
                if d < min_dist { min_dist = d; }
            }
            let vtol = vertex_tolerance(brep, vi);
            if min_dist > vtol && min_dist < f64::MAX {
                updates.push((vi, min_dist));
            }
        }
    }
    for (vi, tol) in updates {
        update_vertex_tolerance(brep, vi, tol);
    }
}

/// ✅ OCCT对齐: 完整 PostTreat — CorrectTolerances + CorrectCurveOnSurface + CorrectPointOnCurve。
pub fn post_treat(brep: &mut BRep, samples_per_edge: usize) {
    correct_tolerances(brep, samples_per_edge);
    correct_curve_on_surface(brep, samples_per_edge);
    correct_point_on_curve(brep);
    same_range(brep);
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{BRep, PrimitiveSolid};

    #[test]
    fn default_tolerance_is_confusion() {
        let brep = BRep::new();
        assert_eq!(vertex_tolerance(&brep, 0), CONFUSION);
        assert_eq!(edge_tolerance(&brep, 0), CONFUSION);
        assert_eq!(face_tolerance(&brep, 0), CONFUSION);
        assert_eq!(model_tolerance(&brep), CONFUSION);
    }

    #[test]
    fn stored_tolerance_returned() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0,
            height: 1.0,
            depth: 1.0,
        });
        brep.geom.edge_tolerance = vec![1e-5; brep.edges.len()];
        assert!((edge_tolerance(&brep, 0) - 1e-5).abs() < 1e-20);
    }

    #[test]
    fn model_tolerance_returns_max() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0,
            height: 1.0,
            depth: 1.0,
        });
        brep.geom.vertex_tolerance = vec![1e-6; brep.vertices.len()];
        brep.geom.edge_tolerance = vec![1e-5; brep.edges.len()];
        // max is 1e-5
        assert!((model_tolerance(&brep) - 1e-5).abs() < 1e-20);
    }

    #[test]
    fn zero_tolerance_falls_back_to_confusion() {
        let mut brep = BRep::new();
        brep.geom.vertex_tolerance = vec![0.0];
        assert_eq!(vertex_tolerance(&brep, 0), CONFUSION);
    }

    // ── Write API tests ───────────────────────────────────────────────────────

    #[test]
    fn set_vertex_tolerance_stores_value() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        set_vertex_tolerance(&mut brep, 0, 1e-4);
        assert!((vertex_tolerance(&brep, 0) - 1e-4).abs() < 1e-20);
    }

    #[test]
    fn update_vertex_tolerance_only_raises() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        set_vertex_tolerance(&mut brep, 0, 1e-4);
        update_vertex_tolerance(&mut brep, 0, 1e-6); // lower — should not change
        assert!((vertex_tolerance(&brep, 0) - 1e-4).abs() < 1e-20);
        update_vertex_tolerance(&mut brep, 0, 1e-3); // higher — should update
        assert!((vertex_tolerance(&brep, 0) - 1e-3).abs() < 1e-20);
    }

    #[test]
    fn set_edge_tolerance_stores_value() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        set_edge_tolerance(&mut brep, 3, 5e-5);
        assert!((edge_tolerance(&brep, 3) - 5e-5).abs() < 1e-20);
    }

    #[test]
    fn update_edge_tolerance_only_raises() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        set_edge_tolerance(&mut brep, 2, 1e-5);
        update_edge_tolerance(&mut brep, 2, 1e-8); // lower — no change
        assert!((edge_tolerance(&brep, 2) - 1e-5).abs() < 1e-20);
        update_edge_tolerance(&mut brep, 2, 2e-5); // higher — updates
        assert!((edge_tolerance(&brep, 2) - 2e-5).abs() < 1e-20);
    }

    #[test]
    fn set_face_tolerance_stores_value() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        set_face_tolerance(&mut brep, 0, 3e-5);
        assert!((face_tolerance(&brep, 0) - 3e-5).abs() < 1e-20);
    }

    #[test]
    fn out_of_range_set_extends_array() {
        let mut brep = BRep::new(); // no entities
        set_vertex_tolerance(&mut brep, 99, 1e-4);
        assert_eq!(brep.geom.vertex_tolerance.len(), 100);
        assert!((brep.geom.vertex_tolerance[99] - 1e-4).abs() < 1e-20);
        // slots before 99 should be CONFUSION
        assert_eq!(brep.geom.vertex_tolerance[0], CONFUSION);
    }

    #[test]
    fn below_confusion_floor_clamped() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        set_vertex_tolerance(&mut brep, 0, 1e-15); // below CONFUSION = 1e-7
        assert_eq!(vertex_tolerance(&brep, 0), CONFUSION);
    }

    #[test]
    fn resize_tolerance_arrays_fills_missing_slots() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        // Arrays start empty for primitives.
        assert!(brep.geom.vertex_tolerance.is_empty());
        resize_tolerance_arrays(&mut brep);
        assert_eq!(brep.geom.vertex_tolerance.len(), 8);
        assert_eq!(brep.geom.edge_tolerance.len(), 12);
        assert_eq!(brep.geom.face_tolerance.len(), 6);
        // All filled with CONFUSION.
        assert!(brep.geom.vertex_tolerance.iter().all(|&t| t == CONFUSION));
    }

    #[test]
    fn finalize_tolerance_hierarchy_propagates_face_to_vertex() {
        // Give face 0 a high tolerance; after finalization all its boundary verts/edges
        // should carry at least that tolerance.
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        resize_tolerance_arrays(&mut brep);
        set_face_tolerance(&mut brep, 0, 1e-4); // face 0 = front face
        finalize_tolerance_hierarchy(&mut brep);

        // All edge tolerances that belong to face 0 should be ≥ 1e-4.
        // Box face 0 has edges 0,1,2,3 (from create_box).
        for &ei in &[0usize, 1, 2, 3] {
            assert!(
                edge_tolerance(&brep, ei) >= 1e-4 - 1e-15,
                "edge {ei} tol should be ≥ 1e-4, got {}",
                edge_tolerance(&brep, ei)
            );
        }
        // Vertices of those edges should be ≥ 1e-4 as well.
        for vi in 0..4usize {
            assert!(
                vertex_tolerance(&brep, vi) >= 1e-4 - 1e-15,
                "vertex {vi} tol should be ≥ 1e-4, got {}",
                vertex_tolerance(&brep, vi)
            );
        }
    }

    #[test]
    fn finalize_tolerance_hierarchy_never_lowers() {
        // Vertices/edges with higher pre-existing tolerance must not be lowered.
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        resize_tolerance_arrays(&mut brep);
        set_vertex_tolerance(&mut brep, 0, 1e-3); // very high vertex tol
        set_face_tolerance(&mut brep, 0, 1e-6);   // lower face tol
        finalize_tolerance_hierarchy(&mut brep);
        // Vertex 0 must still be 1e-3.
        assert!((vertex_tolerance(&brep, 0) - 1e-3).abs() < 1e-20);
    }

    #[test]
    fn correct_tolerances_runs_without_panic() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 2.0, depth: 3.0,
        });
        // Should not panic on a valid box BRep.
        correct_tolerances(&mut brep, 5);
        // All tolerances should be at least CONFUSION after processing.
        for vi in 0..brep.vertices.len() {
            assert!(vertex_tolerance(&brep, vi) >= CONFUSION);
        }
        for ei in 0..brep.edges.len() {
            assert!(edge_tolerance(&brep, ei) >= CONFUSION);
        }
    }

    #[test]
    fn same_range_sets_flag() {
        let mut brep = BRep::from_primitive(PrimitiveSolid::Box {
            width: 1.0, height: 1.0, depth: 1.0,
        });
        // Initially no same_range flag.
        assert!(brep.geom.edge_same_range.is_empty());
        same_range(&mut brep);
        // After same_range, flags should be set for all edges.
        assert_eq!(brep.geom.edge_same_range.len(), brep.edges.len());
        assert!(brep.geom.edge_same_range.iter().all(|&f| f));
    }
}
