// Auto-generated PaveFiller stage reference tests.
// Generated by tools/gen_pavefiller_tests.py
// Do not edit manually.

use glam::{DVec3, DAffine3};
use rcad_algorithms::brep_tools::transform_shape_topods;
use rcad_algorithms::pave_filler::PaveFiller;
use rcad_algorithms::bopds::ds::DS;
use rcad_algorithms::tolerance::TOLERANCE_ABS;
use rcad_kernel::topods;
use rcad_modeling::{make_box_brep, make_sphere_brep, make_cylinder_brep, make_cone_brep};

/// Stage counts expected from OCCT reference.
#[derive(Debug, Clone)]
struct StageExpect {
    stage_name: &'static str,
    nV: usize,
    nE: usize,
    nF: usize,
    nNewV: usize,
    nNewE: usize,
    nIC: usize,
    nPB: usize,
    interf_VV: usize,
    interf_VE: usize,
    interf_VF: usize,
    interf_EE: usize,
    interf_EF: usize,
    interf_FF: usize,
}

/// Run PaveFiller for two shapes and check against OCCT reference.
fn check_pf_stages(
    a: &topods::BRep, b: &topods::BRep,
    label: &str, stages: &[StageExpect],
) {
    // Run PaveFiller
    let mut ds = DS::new_empty();
    let mut brep = topods::BRep::new();
    {
        let mut filler = PaveFiller::new(&mut ds);
        filler.brep = Some(&mut brep);
        filler.set_run_parallel(false);
        filler.configure_fuzzy(TOLERANCE_ABS);
        filler.set_non_destructive(false);
        filler.configure_glue(false, TOLERANCE_ABS);
        filler.set_use_obb(false);
        filler.stop_after = Some("after_Init".into());
        filler.perform(a, b);
    }

    // Check Init DS state (match against _init_direct entry)
    // stop_after ensures we check before any intersection processing.
    if let Some(init) = stages.first() {
        assert_eq!(ds.vertices.len(), init.nV,
            "{}: Init nV mismatch", label);
        assert_eq!(ds.edges.len(), init.nE,
            "{}: Init nE mismatch", label);
        assert_eq!(ds.faces.len(), init.nF,
            "{}: Init nF mismatch", label);
        assert_eq!(ds.intersection_curves.len(), init.nIC,
            "{}: Init nIC mismatch", label);
        assert_eq!(ds.interf_vv.len(), init.interf_VV,
            "{}: Init VV mismatch", label);
        assert_eq!(ds.interf_ve.len(), init.interf_VE,
            "{}: Init VE mismatch", label);
        assert_eq!(ds.interf_vf.len(), init.interf_VF,
            "{}: Init VF mismatch", label);
        assert_eq!(ds.interf_ee.len(), init.interf_EE,
            "{}: Init EE mismatch", label);
        assert_eq!(ds.interf_ef.len(), init.interf_EF,
            "{}: Init EF mismatch", label);
        assert_eq!(ds.interf_ff.len(), init.interf_FF,
            "{}: Init FF mismatch", label);
    }
}


/// ======================================================================
/// P002: BOX x BOX (rotated)
/// OCCT exemplar: bopcommon_simple/C3
/// Shapes: BOX x BOX, position: ROTATED
/// ======================================================================
#[test]
fn pf_stage_box_x_box_rotated() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (BOX) + transform
    let mut b = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box b");
    // Rotate b 45° around Z axis
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(45.0_f64.to_radians()));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 16,
            nE: 24,
            nF: 12,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
        StageExpect {
            stage_name: "after_Init",
            nV: 16,
            nE: 24,
            nF: 12,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P002", stages);
}


/// ======================================================================
/// P003: CYLINDER x BOX
/// OCCT exemplar: bopcommon_simple/R1
/// Shapes: CYLINDER x BOX, position: OVERLAP
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_box() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (BOX)
    let mut b = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box b");
    // Offset b slightly to create overlap
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.0, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P003", stages);
}


/// ======================================================================
/// P004: CYLINDER x BOX (rotated)
/// OCCT exemplar: bopcommon_simple/R2
/// Shapes: CYLINDER x BOX, position: ROTATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_box_rotated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (BOX) + transform
    let mut b = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box b");
    // Rotate b 45° around Z axis
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(45.0_f64.to_radians()));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P004", stages);
}


/// ======================================================================
/// P005: BOX x BOX
/// OCCT exemplar: bopcommon_simple/A1
/// Shapes: BOX x BOX, position: OVERLAP
/// ======================================================================
#[test]
fn pf_stage_box_x_box() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (BOX)
    let mut b = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box b");
    // Offset b slightly to create overlap
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.0, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 16,
            nE: 24,
            nF: 12,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P005", stages);
}


/// ======================================================================
/// P006: CYLINDER x CONE (rotated+translated)
/// OCCT exemplar: bopcommon_simple/ZK2
/// Shapes: CYLINDER x CONE, position: ROTATED+TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_cone_rotated_translated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (CONE) + transform
    let mut b = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone b");
    // Rotate 30°, then translate
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(30.0_f64.to_radians()));
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.2, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P006", stages);
}


/// ======================================================================
/// P007: CONE x CONE (translated)
/// OCCT exemplar: bopcommon_simple/ZM1
/// Shapes: CONE x CONE, position: TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cone_x_cone_translated() {
    // Construct shape A (CONE)
    let a = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone a");

    // Construct shape B (CONE) + transform
    let mut b = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone b");
    // Translate b by (0.3, 0.3, 0)
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.3, 0.3, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P007", stages);
}


/// ======================================================================
/// P008: BOX x CONE (translated)
/// OCCT exemplar: bopcommon_simple/ZG1
/// Shapes: BOX x CONE, position: TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_box_x_cone_translated() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (CONE) + transform
    let mut b = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone b");
    // Translate b by (0.3, 0.3, 0)
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.3, 0.3, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P008", stages);
}


/// ======================================================================
/// P009: CYLINDER x SPHERE (rotated+translated)
/// OCCT exemplar: bopcommon_simple/ZI1
/// Shapes: CYLINDER x SPHERE, position: ROTATED+TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_sphere_rotated_translated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (SPHERE) + transform
    let mut b = make_sphere_brep(DVec3::ZERO, 1.0)
        .expect("sphere b");
    // Rotate 30°, then translate
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(30.0_f64.to_radians()));
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.2, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 4,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P009", stages);
}


/// ======================================================================
/// P010: BOX x CYLINDER (translated)
/// OCCT exemplar: bopcommon_simple/ZO1
/// Shapes: BOX x CYLINDER, position: TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_box_x_cylinder_translated() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (CYLINDER) + transform
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Translate b by (0.3, 0.3, 0)
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.3, 0.3, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P010", stages);
}


/// ======================================================================
/// P011: CYLINDER x CYLINDER (translated)
/// OCCT exemplar: bopcommon_simple/ZD1
/// Shapes: CYLINDER x CYLINDER, position: TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_cylinder_translated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (CYLINDER) + transform
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Translate b by (0.3, 0.3, 0)
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.3, 0.3, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P011", stages);
}


/// ======================================================================
/// P012: CYLINDER x CYLINDER (rotated+translated)
/// OCCT exemplar: bopcommon_simple/ZD5
/// Shapes: CYLINDER x CYLINDER, position: ROTATED+TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_cylinder_rotated_translated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (CYLINDER) + transform
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Rotate 30°, then translate
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(30.0_f64.to_radians()));
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.2, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P012", stages);
}


/// ======================================================================
/// P013: CYLINDER x CYLINDER (rotated)
/// OCCT exemplar: bopcommon_simple/ZD8
/// Shapes: CYLINDER x CYLINDER, position: ROTATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_cylinder_rotated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (CYLINDER) + transform
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Rotate b 45° around Z axis
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(45.0_f64.to_radians()));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P013", stages);
}


/// ======================================================================
/// P014: BOX x CONE (rotated+translated)
/// OCCT exemplar: bopcommon_simple/ZG4
/// Shapes: BOX x CONE, position: ROTATED+TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_box_x_cone_rotated_translated() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (CONE) + transform
    let mut b = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone b");
    // Rotate 30°, then translate
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(30.0_f64.to_radians()));
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.2, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P014", stages);
}


/// ======================================================================
/// P016: CYLINDER x SPHERE (translated)
/// OCCT exemplar: bopcommon_simple/ZI8
/// Shapes: CYLINDER x SPHERE, position: TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_sphere_translated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (SPHERE) + transform
    let mut b = make_sphere_brep(DVec3::ZERO, 1.0)
        .expect("sphere b");
    // Translate b by (0.3, 0.3, 0)
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.3, 0.3, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 4,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P016", stages);
}


/// ======================================================================
/// P017: BOX x CYLINDER
/// OCCT exemplar: bopcommon_simple/ZP3
/// Shapes: BOX x CYLINDER, position: OVERLAP
/// ======================================================================
#[test]
fn pf_stage_box_x_cylinder() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (CYLINDER)
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Offset b slightly to create overlap
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.0, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P017", stages);
}


/// ======================================================================
/// P018: CYLINDER x BOX (translated)
/// OCCT exemplar: bopcommon_simple/Z9
/// Shapes: CYLINDER x BOX, position: TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_box_translated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (BOX) + transform
    let mut b = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box b");
    // Translate b by (0.3, 0.3, 0)
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.3, 0.3, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P018", stages);
}


/// ======================================================================
/// P019: CYLINDER x CONE (translated)
/// OCCT exemplar: bopcommon_simple/ZK1
/// Shapes: CYLINDER x CONE, position: TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_cone_translated() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (CONE) + transform
    let mut b = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone b");
    // Translate b by (0.3, 0.3, 0)
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.3, 0.3, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P019", stages);
}


/// ======================================================================
/// P020: CONE x CONE (rotated+translated)
/// OCCT exemplar: bopcommon_simple/ZM8
/// Shapes: CONE x CONE, position: ROTATED+TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_cone_x_cone_rotated_translated() {
    // Construct shape A (CONE)
    let a = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone a");

    // Construct shape B (CONE) + transform
    let mut b = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone b");
    // Rotate 30°, then translate
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(30.0_f64.to_radians()));
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.2, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P020", stages);
}


/// ======================================================================
/// P021: BOX x CYLINDER (rotated+translated)
/// OCCT exemplar: bopcommon_simple/ZO7
/// Shapes: BOX x CYLINDER, position: ROTATED+TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_box_x_cylinder_rotated_translated() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (CYLINDER) + transform
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Rotate 30°, then translate
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(30.0_f64.to_radians()));
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.2, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P021", stages);
}


/// ======================================================================
/// P023: BOX x BOX (rotated+translated)
/// OCCT exemplar: bopcommon_simple/Q9
/// Shapes: BOX x BOX, position: ROTATED+TRANSLATED
/// ======================================================================
#[test]
fn pf_stage_box_x_box_rotated_translated() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (BOX) + transform
    let mut b = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box b");
    // Rotate 30°, then translate
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(30.0_f64.to_radians()));
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.2, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 16,
            nE: 24,
            nF: 12,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P023", stages);
}


/// ======================================================================
/// P024: CYLINDER x CYLINDER
/// OCCT exemplar: bopcommon_simple/ZD2
/// Shapes: CYLINDER x CYLINDER, position: OVERLAP
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_cylinder() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (CYLINDER)
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Offset b slightly to create overlap
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.0, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P024", stages);
}


/// ======================================================================
/// P025: CYLINDER x SPHERE
/// OCCT exemplar: bopcommon_simple/ZJ6
/// Shapes: CYLINDER x SPHERE, position: OVERLAP
/// ======================================================================
#[test]
fn pf_stage_cylinder_x_sphere() {
    // Construct shape A (CYLINDER)
    let a = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder a");

    // Construct shape B (SPHERE)
    let mut b = make_sphere_brep(DVec3::ZERO, 1.0)
        .expect("sphere b");
    // Offset b slightly to create overlap
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.0, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 4,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P025", stages);
}


/// ======================================================================
/// P026: CONE x CONE
/// OCCT exemplar: bopcommon_simple/ZM3
/// Shapes: CONE x CONE, position: OVERLAP
/// ======================================================================
#[test]
fn pf_stage_cone_x_cone() {
    // Construct shape A (CONE)
    let a = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone a");

    // Construct shape B (CONE)
    let mut b = make_cone_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 0.5, 2.0)
        .expect("cone b");
    // Offset b slightly to create overlap
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.0, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 4,
            nE: 6,
            nF: 6,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P026", stages);
}


/// ======================================================================
/// P028: BOX x CYLINDER (rotated)
/// OCCT exemplar: bopfuse_simple/ZP6
/// Shapes: BOX x CYLINDER, position: ROTATED
/// ======================================================================
#[test]
fn pf_stage_box_x_cylinder_rotated() {
    // Construct shape A (BOX)
    let a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("box a");

    // Construct shape B (CYLINDER) + transform
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Rotate b 45° around Z axis
    transform_shape_topods(&mut b, DAffine3::from_rotation_z(45.0_f64.to_radians()));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P028", stages);
}


/// ======================================================================
/// P029: PRISM x CYLINDER
/// OCCT exemplar: bopsection/A1
/// Shapes: PRISM x CYLINDER, position: OVERLAP
/// ======================================================================
#[test]
fn pf_stage_prism_x_cylinder() {
    // Construct shape A (PRISM)
    let mut a = make_box_brep(DVec3::ZERO, DVec3::X, DVec3::Y, 1.0, 1.0, 1.0)
        .expect("prism a");

    // Construct shape B (CYLINDER)
    let mut b = make_cylinder_brep(DVec3::ZERO, DVec3::Z, DVec3::X, 1.0, 2.0)
        .expect("cylinder b");
    // Offset b slightly to create overlap
    transform_shape_topods(&mut b, DAffine3::from_translation(DVec3::new(0.2, 0.0, 0.0)));


    // OCCT reference stages
    let stages: &[StageExpect] = &[
        StageExpect {
            stage_name: "after_Init",
            nV: 10,
            nE: 15,
            nF: 9,
            nNewV: 0,
            nNewE: 0,
            nIC: 0,
            nPB: 0,
            interf_VV: 0,
            interf_VE: 0,
            interf_VF: 0,
            interf_EE: 0,
            interf_EF: 0,
            interf_FF: 0,
        },
    ];

    check_pf_stages(&a, &b, "P029", stages);
}
